"""Add 50 more schemes to reach 150 total.

Focus: TAHDCO, TAMCO, Central SC/ST, Women, Education, Health, Agri.

Usage:  python -m scripts.seed_batch_150
Idempotent: existing slugs are skipped.
"""
from datetime import date
from app.database import SessionLocal
from app.models.scheme import Scheme

V = date(2026, 9, 22)
BY = "Admin User"
CATS = ["General", "OBC", "BC", "MBC", "SC", "ST"]


def s(**kw):
    kw.setdefault("status", "active")
    kw.setdefault("verified_by", BY)
    kw.setdefault("last_verified", V)
    return kw


SCHEMES = [
    # ============================================================
    # TAHDCO (SC/ST) — 10 schemes
    # ============================================================
    s(slug="tahdco-education-loan", short_name="TAHDCO Edu", category="sc_st",
      name={"en":"TAHDCO Education Loan Scheme","ta":"டஹ்ட்கோ கல்விக் கடன் திட்டம்","hi":"TAHDCO शिक्षा ऋण योजना"},
      department={"en":"TAHDCO, Government of Tamil Nadu","ta":"டஹ்ட்கோ, தமிழ்நாடு அரசு","hi":"TAHDCO, तमिलनाडु सरकार"},
      description={"en":"Education loan up to ₹5 lakh for SC/ST students pursuing higher education in India or abroad.","ta":"SC/ST மாணவர்களுக்கு உயர் கல்விக்கு ₹5 லட்சம் வரை கல்விக் கடன்.","hi":"SC/ST छात्रों को उच्च शिक्षा के लिए ₹5 लाख तक शिक्षा ऋण।"},
      min_age=17, max_age=35, max_income=250000, eligible_categories=["SC","ST"],
      eligible_genders=None, eligible_business_status=["new"], education="12th Pass",
      max_loan=500000, interest_rate="4% – 6%", subsidy_percent=0,
      moratorium="Course duration + 1 year", repayment_years="5 years",
      documents=["Aadhaar Card","Caste certificate","Income certificate","Admission letter","Fee structure"],
      source_url="https://www.tahdco.tn.gov.in/"),

    s(slug="tahdco-land-purchase", short_name="TAHDCO Land", category="sc_st",
      name={"en":"TAHDCO Land Purchase Scheme","ta":"டஹ்ட்கோ நிலம் வாங்கும் திட்டம்","hi":"TAHDCO भूमि खरीद योजना"},
      department={"en":"TAHDCO, Government of Tamil Nadu","ta":"டஹ்ட்கோ, தமிழ்நாடு அரசு","hi":"TAHDCO, तमिलनाडु सरकार"},
      description={"en":"Financial assistance for SC/ST to purchase agricultural land up to 2 acres with 50% subsidy.","ta":"SC/ST விவசாயிகளுக்கு 2 ஏக்கர் வரை நிலம் வாங்க 50% மானியம்.","hi":"SC/ST किसानों को 2 एकड़ तक कृषि भूमि खरीदने के लिए 50% सब्सिडी।"},
      min_age=18, max_age=60, max_income=200000, eligible_categories=["SC","ST"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=500000, interest_rate="4%", subsidy_percent=50,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Caste certificate","Income certificate","Land documents"],
      source_url="https://www.tahdco.tn.gov.in/"),

    s(slug="tahdco-fast-power", short_name="Fast Power", category="sc_st",
      name={"en":"Fast Track Power Supply Scheme","ta":"விரைவு மின் இணைப்பு திட்டம்","hi":"फास्ट ट्रैक बिजली आपूर्ति योजना"},
      department={"en":"TAHDCO, Government of Tamil Nadu","ta":"டஹ்ட்கோ, தமிழ்நாடு அரசு","hi":"TAHDCO, तमिलनाडु सरकार"},
      description={"en":"90% subsidy on electricity connection cost for SC/ST entrepreneurs setting up small businesses.","ta":"SC/ST தொழில்முனைவோருக்கு மின் இணைப்பு செலவில் 90% மானியம்.","hi":"SC/ST उद्यमियों को बिजली कनेक्शन लागत पर 90% सब्सिडी।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=["SC","ST"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=90,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Caste certificate","Electricity application"],
      source_url="https://www.tahdco.tn.gov.in/"),

    s(slug="tahdco-marriage-assistance", short_name="Marriage Help", category="sc_st",
      name={"en":"TAHDCO Marriage Assistance","ta":"டஹ்ட்கோ திருமண உதவி","hi":"TAHDCO विवाह सहायता"},
      department={"en":"TAHDCO, Government of Tamil Nadu","ta":"டஹ்ட்கோ, தமிழ்நாடு அரசு","hi":"TAHDCO, तमिलनाडु सरकार"},
      description={"en":"Marriage assistance of ₹25,000 for SC/ST families with income below ₹72,000 per annum.","ta":"ஆண்டு வருமானம் ₹72,000-க்கு கீழ் உள்ள SC/ST குடும்பங்களுக்கு ₹25,000 திருமண உதவி.","hi":"वार्षिक आय ₹72,000 से कम वाले SC/ST परिवारों को ₹25,000 विवाह सहायता।"},
      min_age=18, max_age=None, max_income=72000, eligible_categories=["SC","ST"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=25000, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Caste certificate","Income certificate","Marriage invitation"],
      source_url="https://www.tahdco.tn.gov.in/"),

    s(slug="tahdco-business-loan", short_name="TAHDCO Loan", category="sc_st",
      name={"en":"TAHDCO Business Loan","ta":"டஹ்ட்கோ வணிகக் கடன்","hi":"TAHDCO व्यावसायिक ऋण"},
      department={"en":"TAHDCO, Government of Tamil Nadu","ta":"டஹ்ட்கோ, தமிழ்நாடு அரசு","hi":"TAHDCO, तमिलनाडु सरकार"},
      description={"en":"Business loan up to ₹10 lakh for SC/ST entrepreneurs with 6% interest subvention.","ta":"SC/ST தொழில்முனைவோருக்கு ₹10 லட்சம் வரை வணிகக் கடன், 6% வட்டி மானியம்.","hi":"SC/ST उद्यमियों को ₹10 लाख तक व्यावसायिक ऋण, 6% ब्याज सब्सिडी।"},
      min_age=21, max_age=55, max_income=300000, eligible_categories=["SC","ST"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=1000000, interest_rate="6% subvention", subsidy_percent=0,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Caste certificate","Project report","Bank statements"],
      source_url="https://www.tahdco.tn.gov.in/"),

    s(slug="tahdco-self-employment", short_name="TNCSH", category="sc_st",
      name={"en":"TAHDCO Self Employment Scheme","ta":"டஹ்ட்கோ சுய வேலைவாய்ப்பு திட்டம்","hi":"TAHDCO स्वरोजगार योजना"},
      department={"en":"TAHDCO, Government of Tamil Nadu","ta":"டஹ்ட்கோ, தமிழ்நாடு அரசு","hi":"TAHDCO, तमिलनाडु सरकार"},
      description={"en":"Self-employment support for SC/ST youth with subsidy up to ₹50,000 for small business setup.","ta":"SC/ST இளைஞர்களுக்கு சிறு வணிகத் தொடக்கத்திற்கு ₹50,000 வரை மானியம்.","hi":"SC/ST युवाओं को छोटे व्यवसाय के लिए ₹50,000 तक सब्सिडी।"},
      min_age=18, max_age=45, max_income=200000, eligible_categories=["SC","ST"],
      eligible_genders=None, eligible_business_status=["new"], education=None,
      max_loan=100000, interest_rate="4% – 8%", subsidy_percent=50,
      moratorium="6 months", repayment_years="3 years",
      documents=["Aadhaar Card","Caste certificate","Income certificate","Business plan"],
      source_url="https://www.tahdco.tn.gov.in/"),

    s(slug="tahdco-dr-ambedkar", short_name="Dr. Ambedkar", category="sc_st",
      name={"en":"Dr. Ambedkar Self Employment Scheme","ta":"டாக்டர் அம்பேத்கர் சுய வேலைவாய்ப்பு","hi":"डॉ. अम्बेडकर स्वरोजगार योजना"},
      department={"en":"TAHDCO, Government of Tamil Nadu","ta":"டஹ்ட்கோ, தமிழ்நாடு அரசு","hi":"TAHDCO, तमिलनाडु सरकार"},
      description={"en":"Loans up to ₹50,000 with 50% subsidy for SC/ST entrepreneurs in petty businesses.","ta":"SC/ST சிறு வணிகர்களுக்கு ₹50,000 வரை கடன், 50% மானியம்.","hi":"SC/ST लघु व्यवसायियों को ₹50,000 तक ऋण, 50% सब्सिडी।"},
      min_age=18, max_age=55, max_income=150000, eligible_categories=["SC","ST"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=50000, interest_rate="4%", subsidy_percent=50,
      moratorium="6 months", repayment_years="3 years",
      documents=["Aadhaar Card","Caste certificate","Income certificate"],
      source_url="https://www.tahdco.tn.gov.in/"),

    s(slug="tahdco-shg-loan", short_name="SHG Loan", category="sc_st",
      name={"en":"TAHDCO SC Women SHG Loan","ta":"டஹ்ட்கோ SC மகளிர் SHG கடன்","hi":"TAHDCO SC महिला SHG ऋण"},
      department={"en":"TAHDCO, Government of Tamil Nadu","ta":"டஹ்ட்கோ, தமிழ்நாடு அரசு","hi":"TAHDCO, तमिलनाडु सरकार"},
      description={"en":"Group loans up to ₹10 lakh for SC women SHGs with 50% subsidy (max ₹5 lakh).","ta":"SC மகளிர் SHG-க்கு ₹10 லட்சம் வரை குழு கடன், 50% மானியம்.","hi":"SC महिला SHG को ₹10 लाख तक समूह ऋण, 50% सब्सिडी।"},
      min_age=18, max_age=60, max_income=None, eligible_categories=["SC"],
      eligible_genders=["female"], eligible_business_status=["new","existing"], education=None,
      max_loan=1000000, interest_rate="4% – 6%", subsidy_percent=50,
      moratorium="6 months", repayment_years="3 years",
      documents=["SHG registration","Aadhaar Card","Bank passbook","Group resolution"],
      source_url="https://www.tahdco.tn.gov.in/"),

    s(slug="tahdco-agri-allied", short_name="Agri Allied", category="sc_st",
      name={"en":"TAHDCO Agriculture & Allied Activities","ta":"டஹ்ட்கோ வேளாண் மற்றும் இணை செயல்பாடுகள்","hi":"TAHDCO कृषि और संबद्ध गतिविधियाँ"},
      department={"en":"TAHDCO, Government of Tamil Nadu","ta":"டஹ்ட்கோ, தமிழ்நாடு அரசு","hi":"TAHDCO, तमिलनाडु सरकार"},
      description={"en":"Financial assistance for SC/ST farmers for dairy, poultry, goat rearing, and fisheries.","ta":"SC/ST விவசாயிகளுக்கு பால், கோழி, ஆடு வளர்ப்பு, மீன்வளத்திற்கு உதவி.","hi":"SC/ST किसानों को डेयरी, पोल्ट्री, बकरी पालन, मत्स्य पालन के लिए सहायता।"},
      min_age=18, max_age=60, max_income=200000, eligible_categories=["SC","ST"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=500000, interest_rate="4% – 6%", subsidy_percent=35,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Caste certificate","Land documents","Project report"],
      source_url="https://www.tahdco.tn.gov.in/"),

    s(slug="tahdco-entrepreneur-dev", short_name="EDP", category="sc_st",
      name={"en":"Entrepreneurship Development Programme","ta":"தொழில்முனைவு மேம்பாட்டுத் திட்டம்","hi":"उद्यमिता विकास कार्यक्रम"},
      department={"en":"TAHDCO, Government of Tamil Nadu","ta":"டஹ்ட்கோ, தமிழ்நாடு அரசு","hi":"TAHDCO, तमिलनाडु सरकार"},
      description={"en":"Training + mentorship for SC/ST youth to start small business with seed capital support.","ta":"SC/ST இளைஞர்களுக்கு பயிற்சி + வழிகாட்டுதல் மற்றும் விதை மூலதனம்.","hi":"SC/ST युवाओं को प्रशिक्षण + मेंटरशिप और सीड कैपिटल सहायता।"},
      min_age=18, max_age=40, max_income=250000, eligible_categories=["SC","ST"],
      eligible_genders=None, eligible_business_status=["new"], education="10th Pass",
      max_loan=200000, interest_rate="5%", subsidy_percent=25,
      moratorium="6 months", repayment_years="3 years",
      documents=["Aadhaar Card","Caste certificate","Education certificate","Training certificate"],
      source_url="https://www.tahdco.tn.gov.in/"),

    # ============================================================
    # TAMCO (Minorities) — 10 schemes
    # ============================================================
    s(slug="tamco-individual-loan", short_name="TAMCO Loan", category="business",
      name={"en":"TAMCO Individual Loan Scheme","ta":"டாம்கோ தனிநபர் கடன் திட்டம்","hi":"TAMCO व्यक्तिगत ऋण योजना"},
      department={"en":"TAMCO, Government of Tamil Nadu","ta":"டாம்கோ, தமிழ்நாடு அரசு","hi":"TAMCO, तमिलनाडु सरकार"},
      description={"en":"Concessional loan up to ₹5 lakh for minority entrepreneurs at 5% interest.","ta":"சிறுபான்மை தொழில்முனைவோருக்கு ₹5 லட்சம் வரை 5% வட்டியில் கடன்.","hi":"अल्पसंख्यक उद्यमियों को ₹5 लाख तक 5% ब्याज पर ऋण।"},
      min_age=21, max_age=55, max_income=200000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=500000, interest_rate="5%", subsidy_percent=0,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Minority certificate","Income certificate","Project report"],
      source_url="https://www.tamco.tn.gov.in/"),

    s(slug="tamco-viraasat", short_name="Viraasat", category="handicraft",
      name={"en":"Viraasat Loan Scheme","ta":"விராசத் கடன் திட்டம்","hi":"विरासत ऋण योजना"},
      department={"en":"TAMCO, Government of Tamil Nadu","ta":"டாம்கோ, தமிழ்நாடு அரசு","hi":"TAMCO, तमिलनाडु सरकार"},
      description={"en":"Loan up to ₹2 lakh for minority artisans to preserve traditional crafts.","ta":"சிறுபான்மை கைவினைஞர்களுக்கு ₹2 லட்சம் வரை பாரம்பரிய கலை பாதுகாப்பு கடன்.","hi":"अल्पसंख्यक कारीगरों को पारंपरिक शिल्प संरक्षण के लिए ₹2 लाख तक ऋण।"},
      min_age=18, max_age=60, max_income=150000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=200000, interest_rate="4% – 6%", subsidy_percent=25,
      moratorium="6 months", repayment_years="3 years",
      documents=["Aadhaar Card","Minority certificate","Craft proof","Bank details"],
      source_url="https://www.tamco.tn.gov.in/"),

    s(slug="tamco-micro-enterprise", short_name="TAMCO Micro", category="women",
      name={"en":"TAMCO Micro Enterprise Loan for SHGs","ta":"TAMCO நுண் நிறுவன கடன் SHG","hi":"TAMCO सूक्ष्म उद्यम ऋण SHG"},
      department={"en":"TAMCO, Government of Tamil Nadu","ta":"டாம்கோ, தமிழ்நாடு அரசு","hi":"TAMCO, तमिलनाडु सरकार"},
      description={"en":"Group loans up to ₹5 lakh for minority women SHGs at 5% interest.","ta":"சிறுபான்மை மகளிர் SHG-க்கு ₹5 லட்சம் வரை 5% வட்டி கடன்.","hi":"अल्पसंख्यक महिला SHG को ₹5 लाख तक 5% ब्याज पर ऋण।"},
      min_age=18, max_age=55, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new","existing"], education=None,
      max_loan=500000, interest_rate="5%", subsidy_percent=0,
      moratorium="6 months", repayment_years="3 years",
      documents=["SHG registration","Aadhaar Card","Minority certificate","Bank passbook"],
      source_url="https://www.tamco.tn.gov.in/"),

    s(slug="tamco-education-loan", short_name="TAMCO Edu", category="business",
      name={"en":"TAMCO Education Loan for Minorities","ta":"TAMCO சிறுபான்மை கல்விக் கடன்","hi":"TAMCO अल्पसंख्यक शिक्षा ऋण"},
      department={"en":"TAMCO, Government of Tamil Nadu","ta":"டாம்கோ, தமிழ்நாடு அரசு","hi":"TAMCO, तमिलनाडु सरकार"},
      description={"en":"Education loan up to ₹2 lakh at 3% interest for minority students.","ta":"சிறுபான்மை மாணவர்களுக்கு ₹2 லட்சம் வரை 3% வட்டி கல்விக் கடன்.","hi":"अल्पसंख्यक छात्रों को ₹2 लाख तक 3% ब्याज पर शिक्षा ऋण।"},
      min_age=17, max_age=30, max_income=150000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education="12th Pass",
      max_loan=200000, interest_rate="3%", subsidy_percent=0,
      moratorium="Course + 6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Minority certificate","Income certificate","Admission letter"],
      source_url="https://www.tamco.tn.gov.in/"),

    s(slug="tamco-professional-loan", short_name="TAMCO Pro", category="business",
      name={"en":"TAMCO Professional Loan Scheme","ta":"TAMCO தொழில்முறை கடன்","hi":"TAMCO व्यावसायिक ऋण"},
      department={"en":"TAMCO, Government of Tamil Nadu","ta":"டாம்கோ, தமிழ்நாடு அரசு","hi":"TAMCO, तमिलनाडु सरकार"},
      description={"en":"Loan up to ₹10 lakh for minority professionals to set up clinics, offices, or shops.","ta":"சிறுபான்மை நிபுணர்கள் அலுவலகங்கள், கிளினிக்குகள் அமைக்க ₹10 லட்சம் வரை கடன்.","hi":"अल्पसंख्यक पेशेवरों को क्लिनिक/कार्यालय स्थापित करने के लिए ₹10 लाख तक ऋण।"},
      min_age=21, max_age=55, max_income=500000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education="Graduate or Diploma",
      max_loan=1000000, interest_rate="5%", subsidy_percent=0,
      moratorium="6 months", repayment_years="7 years",
      documents=["Aadhaar Card","Minority certificate","Degree certificate","Project report"],
      source_url="https://www.tamco.tn.gov.in/"),

    s(slug="tamco-auto-loan", short_name="TAMCO Auto", category="business",
      name={"en":"TAMCO Auto Loan for Minorities","ta":"TAMCO ஆட்டோ கடன்","hi":"TAMCO ऑटो ऋण"},
      department={"en":"TAMCO, Government of Tamil Nadu","ta":"டாம்கோ, தமிழ்நாடு அரசு","hi":"TAMCO, तमिलनाडु सरकार"},
      description={"en":"Loan for purchase of auto rickshaw or small commercial vehicle for minority drivers.","ta":"சிறுபான்மை ஓட்டுநர்களுக்கு ஆட்டோ அல்லது சிறு வணிக வாகனம் வாங்க கடன்.","hi":"अल्पसंख्यक चालकों को ऑटो या छोटा वाणिज्यिक वाहन खरीदने के लिए ऋण।"},
      min_age=21, max_age=55, max_income=150000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=300000, interest_rate="5% – 7%", subsidy_percent=0,
      moratorium="3 months", repayment_years="4 years",
      documents=["Aadhaar Card","Minority certificate","Driving licence","Vehicle quotation"],
      source_url="https://www.tamco.tn.gov.in/"),

    s(slug="tamco-skill-dev", short_name="TAMCO Skill", category="youth",
      name={"en":"TAMCO Skill Development Program","ta":"TAMCO திறன் மேம்பாட்டு திட்டம்","hi":"TAMCO कौशल विकास कार्यक्रम"},
      department={"en":"TAMCO, Government of Tamil Nadu","ta":"டாம்கோ, தமிழ்நாடு அரசு","hi":"TAMCO, तमिलनाडु सरकार"},
      description={"en":"Free skill training for minority youth in IT, tailoring, hospitality, and driving with placement support.","ta":"சிறுபான்மை இளைஞர்களுக்கு IT, தையல், விருந்தோம்பல், ஓட்டுநர் திறன் பயிற்சி.","hi":"अल्पसंख्यक युवाओं को IT, टेलरिंग, आतिथ्य, ड्राइविंग में मुफ्त कौशल प्रशिक्षण।"},
      min_age=18, max_age=35, max_income=200000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Minority certificate","Education certificate"],
      source_url="https://www.tamco.tn.gov.in/"),

    s(slug="tamco-shg-market", short_name="TAMCO Market", category="women",
      name={"en":"TAMCO SHG Marketing Support","ta":"TAMCO SHG சந்தை ஆதரவு","hi":"TAMCO SHG विपणन सहायता"},
      department={"en":"TAMCO, Government of Tamil Nadu","ta":"டாம்கோ, தமிழ்நாடு அரசு","hi":"TAMCO, तमिलनाडु सरकार"},
      description={"en":"Marketing support + exhibition stalls for minority women SHG products.","ta":"சிறுபான்மை மகளிர் SHG தயாரிப்புகளுக்கு சந்தை ஆதரவு + கண்காட்சி.","hi":"अल्पसंख्यक महिला SHG उत्पादों के लिए विपणन सहायता + प्रदर्शनी।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["SHG registration","Product details","Bank passbook"],
      source_url="https://www.tamco.tn.gov.in/"),

    s(slug="tamco-marriage", short_name="TAMCO Marriage", category="business",
      name={"en":"TAMCO Marriage Assistance","ta":"TAMCO திருமண உதவி","hi":"TAMCO विवाह सहायता"},
      department={"en":"TAMCO, Government of Tamil Nadu","ta":"டாம்கோ, தமிழ்நாடு அரசு","hi":"TAMCO, तमिलनाडु सरकार"},
      description={"en":"Marriage assistance up to ₹25,000 for minority families below income limit.","ta":"வரம்பிற்குக் கீழ் உள்ள சிறுபான்மை குடும்பங்களுக்கு ₹25,000 வரை திருமண உதவி.","hi":"आय सीमा से नीचे अल्पसंख्यक परिवारों को ₹25,000 तक विवाह सहायता।"},
      min_age=18, max_age=None, max_income=72000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=25000, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Minority certificate","Income certificate"],
      source_url="https://www.tamco.tn.gov.in/"),

    s(slug="tamco-covid-relief", short_name="TAMCO Relief", category="business",
      name={"en":"TAMCO Business Revival Loan","ta":"TAMCO வணிக மீட்பு கடன்","hi":"TAMCO व्यवसाय पुनरुद्धार ऋण"},
      department={"en":"TAMCO, Government of Tamil Nadu","ta":"டாம்கோ, தமிழ்நாடு அரசு","hi":"TAMCO, तमिलनाडु सरकार"},
      description={"en":"Working capital loan up to ₹1 lakh for minority businesses affected by economic disruptions.","ta":"பொருளாதார பாதிப்புக்கு உள்ளான சிறுபான்மை வணிகங்களுக்கு ₹1 லட்சம் வரை மூலதனக் கடன்.","hi":"आर्थिक व्यवधान से प्रभावित अल्पसंख्यक व्यवसायों को ₹1 लाख तक कार्यशील पूंजी ऋण।"},
      min_age=21, max_age=60, max_income=200000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=100000, interest_rate="4%", subsidy_percent=25,
      moratorium="6 months", repayment_years="3 years",
      documents=["Aadhaar Card","Minority certificate","Business proof","Bank statements"],
      source_url="https://www.tamco.tn.gov.in/"),

    # ============================================================
    # Central SC/ST & Minorities — 10 schemes
    # ============================================================
    s(slug="vcf-sc", short_name="VCF-SC", category="sc_st",
      name={"en":"Venture Capital Fund for Scheduled Castes","ta":"ஆதிதிராவிடர் வென்ச்சர் மூலதன நிதி","hi":"अनुसूचित जाति वेंचर कैपिटल फंड"},
      department={"en":"Ministry of Social Justice","ta":"சமூக நீதி அமைச்சகம்","hi":"सामाजिक न्याय मंत्रालय"},
      description={"en":"Equity funding up to ₹5 crore for SC entrepreneurs with viable business plans.","ta":"SC தொழில்முனைவோருக்கு ₹5 கோடி வரை பங்கு நிதி.","hi":"SC उद्यमियों को ₹5 करोड़ तक इक्विटी फंडिंग।"},
      min_age=18, max_age=55, max_income=None, eligible_categories=["SC"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=50000000, interest_rate="Equity", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Caste certificate","Business plan","Financial statements"],
      source_url="https://socialjustice.gov.in/"),

    s(slug="vcf-bc", short_name="VCF-BC", category="business",
      name={"en":"Venture Capital Fund for Backward Classes","ta":"பின்தங்கிய வகுப்பு வென்ச்சர் நிதி","hi":"पिछड़ा वर्ग वेंचर कैपिटल फंड"},
      department={"en":"Ministry of Social Justice","ta":"சமூக நீதி அமைச்சகம்","hi":"सामाजिक न्याय मंत्रालय"},
      description={"en":"Equity funding up to ₹5 crore for OBC entrepreneurs with scalable businesses.","ta":"OBC தொழில்முனைவோருக்கு ₹5 கோடி வரை பங்கு நிதி.","hi":"OBC उद्यमियों को ₹5 करोड़ तक इक्विटी फंडिंग।"},
      min_age=18, max_age=55, max_income=None, eligible_categories=["OBC","BC","MBC"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=50000000, interest_rate="Equity", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","OBC certificate","Business plan","Financial statements"],
      source_url="https://socialjustice.gov.in/"),

    s(slug="nbcfdc-loan", short_name="NBCFDC", category="business",
      name={"en":"NBCFDC Loan for Backward Classes","ta":"NBCFDC பின்தங்கிய வகுப்பு கடன்","hi":"NBCFDC पिछड़ा वर्ग ऋण"},
      department={"en":"National Backward Classes Finance & Dev Corp","ta":"தேசிய பின்தங்கிய வகுப்பு நிதிக் கழகம்","hi":"राष्ट्रीय पिछड़ा वर्ग वित्त निगम"},
      description={"en":"Concessional loans up to ₹15 lakh for OBC entrepreneurs at 5% interest.","ta":"OBC தொழில்முனைவோருக்கு ₹15 லட்சம் வரை 5% வட்டி கடன்.","hi":"OBC उद्यमियों को ₹15 लाख तक 5% ब्याज पर ऋण।"},
      min_age=18, max_age=60, max_income=300000, eligible_categories=["OBC","BC","MBC"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=1500000, interest_rate="5%", subsidy_percent=0,
      moratorium="6 months", repayment_years="7 years",
      documents=["Aadhaar Card","OBC certificate","Income certificate","Project report"],
      source_url="https://www.nbcfdc.gov.in/"),

    s(slug="pm-ajay", short_name="PM-AJAY", category="sc_st",
      name={"en":"PM Anusuchit Jaati Abhyuday Yojana","ta":"PM ஆதிதிராவிடர் முன்னேற்ற திட்டம்","hi":"पीएम अनुसूचित जाति अभ्युदय योजना"},
      department={"en":"Ministry of Social Justice","ta":"சமூக நீதி அமைச்சகம்","hi":"सामाजिक न्याय मंत्रालय"},
      description={"en":"Skill development + entrepreneurship support for SC communities with 50% subsidy.","ta":"SC சமூகங்களுக்கு திறன் மேம்பாடு + தொழில்முனைவு ஆதரவு, 50% மானியம்.","hi":"SC समुदायों को कौशल विकास + उद्यमिता सहायता, 50% सब्सिडी।"},
      min_age=18, max_age=45, max_income=250000, eligible_categories=["SC"],
      eligible_genders=None, eligible_business_status=["new"], education=None,
      max_loan=200000, interest_rate="4%", subsidy_percent=50,
      moratorium="6 months", repayment_years="3 years",
      documents=["Aadhaar Card","Caste certificate","Income certificate"],
      source_url="https://socialjustice.gov.in/"),

    s(slug="nstfdc-loan", short_name="NSTFDC", category="sc_st",
      name={"en":"NSTFDC Loan for Tribal Entrepreneurs","ta":"NSTFDC பழங்குடி தொழில்முனைவோர் கடன்","hi":"NSTFDC जनजातीय उद्यमी ऋण"},
      department={"en":"National Scheduled Tribes Finance & Dev Corp","ta":"தேசிய பழங்குடியினர் நிதிக் கழகம்","hi":"राष्ट्रीय जनजातीय वित्त निगम"},
      description={"en":"Concessional loans up to ₹10 lakh for ST entrepreneurs at 4% interest.","ta":"ST தொழில்முனைவோருக்கு ₹10 லட்சம் வரை 4% வட்டி கடன்.","hi":"ST उद्यमियों को ₹10 लाख तक 4% ब्याज पर ऋण।"},
      min_age=18, max_age=55, max_income=200000, eligible_categories=["ST"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=1000000, interest_rate="4%", subsidy_percent=0,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Tribe certificate","Project report","Bank statements"],
      source_url="https://www.nstfdc.tribal.gov.in/"),

    s(slug="pm-vikas", short_name="PM VIKAS", category="business",
      name={"en":"PM Virasat Ka Samvardhan (PM VIKAS)","ta":"PM விராசத் கா சம்வர்தன்","hi":"पीएम विरासत का संवर्धन"},
      department={"en":"Ministry of Minority Affairs","ta":"சிறுபான்மையினர் நல அமைச்சகம்","hi":"अल्पसंख्यक मामलों का मंत्रालय"},
      description={"en":"Skill development + entrepreneurship support for minorities, especially women artisans.","ta":"சிறுபான்மையினர், குறிப்பாக பெண் கைவினைஞர்களுக்கு திறன் + தொழில் ஆதரவு.","hi":"अल्पसंख्यकों, विशेषकर महिला कारीगरों के लिए कौशल + उद्यमिता सहायता।"},
      min_age=18, max_age=45, max_income=250000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=200000, interest_rate="5%", subsidy_percent=50,
      moratorium="6 months", repayment_years="3 years",
      documents=["Aadhaar Card","Minority certificate","Training certificate"],
      source_url="https://www.minorityaffairs.gov.in/"),

    s(slug="pm-daksh", short_name="PM-DAKSH", category="youth",
      name={"en":"PM-DAKSH Skill Development","ta":"PM-DAKSH திறன் மேம்பாடு","hi":"PM-DAKSH कौशल विकास"},
      department={"en":"Ministry of Social Justice","ta":"சமூக நீதி அமைச்சகம்","hi":"सामाजिक न्याय मंत्रालय"},
      description={"en":"Free skill training for SC/ST/OBC and women in 200+ trades with placement support.","ta":"SC/ST/OBC மற்றும் பெண்களுக்கு 200+ தொழில்களில் இலவச பயிற்சி.","hi":"SC/ST/OBC और महिलाओं को 200+ ट्रेडों में मुफ्त प्रशिक्षण।"},
      min_age=18, max_age=45, max_income=300000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Caste certificate","Education certificate"],
      source_url="https://pmdaksh.dosje.gov.in/"),

    s(slug="nssf", short_name="NSSF", category="sc_st",
      name={"en":"National Safai Karamcharis Finance & Dev Corp","ta":"தேசிய சுத்திகரிப்பாளர் நிதிக் கழகம்","hi":"राष्ट्रीय सफाई कर्मचारी वित्त निगम"},
      department={"en":"Ministry of Social Justice","ta":"சமூக நீதி அமைச்சகம்","hi":"सामाजिक न्याय मंत्रालय"},
      description={"en":"Concessional loans up to ₹15 lakh for safai karamcharis and their dependents.","ta":"சுத்திகரிப்பாளர்கள் மற்றும் அவர்களின் சார்ந்தோருக்கு ₹15 லட்சம் வரை கடன்.","hi":"सफाई कर्मचारियों और उनके आश्रितों को ₹15 लाख तक ऋण।"},
      min_age=18, max_age=55, max_income=300000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=1500000, interest_rate="4% – 6%", subsidy_percent=0,
      moratorium="6 months", repayment_years="7 years",
      documents=["Aadhaar Card","Safai Karamchari certificate","Income certificate"],
      source_url="https://nskfdc.nic.in/"),

    s(slug="pmo-scholarship-top", short_name="PM YASASVI", category="sc_st",
      name={"en":"PM YASASVI Scholarship for OBC/EBC/DNT","ta":"PM YASASVI உதவித்தொகை","hi":"पीएम यशस्वी छात्रवृत्ति"},
      department={"en":"Ministry of Social Justice","ta":"சமூக நீதி அமைச்சகம்","hi":"सामाजिक न्याय मंत्रालय"},
      description={"en":"Scholarship up to ₹1.25 lakh/year for OBC/EBC/DNT students in top schools.","ta":"OBC/EBC/DNT மாணவர்களுக்கு ஆண்டுக்கு ₹1.25 லட்சம் வரை உதவித்தொகை.","hi":"OBC/EBC/DNT छात्रों को वार्षिक ₹1.25 लाख तक छात्रवृत्ति।"},
      min_age=14, max_age=25, max_income=250000, eligible_categories=["OBC","BC","MBC"],
      eligible_genders=None, eligible_business_status=["new"], education="10th Pass",
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","OBC certificate","Income certificate","School certificate"],
      source_url="https://yet.nta.ac.in/"),

    s(slug="nsfdc-education", short_name="NSFDC Edu", category="sc_st",
      name={"en":"NSFDC Education Loan","ta":"NSFDC கல்விக் கடன்","hi":"NSFDC शिक्षा ऋण"},
      department={"en":"National Scheduled Castes Finance & Dev Corp","ta":"தேசிய ஆதிதிராவிடர் நிதிக் கழகம்","hi":"राष्ट्रीय अनुसूचित जाति वित्त निगम"},
      description={"en":"Education loan up to ₹20 lakh at 6% interest for SC students in professional courses.","ta":"SC மாணவர்களுக்கு தொழில்முறை படிப்புகளுக்கு ₹20 லட்சம் வரை 6% வட்டி கடன்.","hi":"SC छात्रों को पेशेवर पाठ्यक्रमों के लिए ₹20 लाख तक 6% ब्याज पर शिक्षा ऋण।"},
      min_age=17, max_age=35, max_income=300000, eligible_categories=["SC"],
      eligible_genders=None, eligible_business_status=["new"], education="12th Pass",
      max_loan=2000000, interest_rate="6%", subsidy_percent=0,
      moratorium="Course + 1 year", repayment_years="7 years",
      documents=["Aadhaar Card","Caste certificate","Income certificate","Admission letter"],
      source_url="https://nsfdc.nic.in/"),

    # ============================================================
    # Women-Focused — 10 schemes
    # ============================================================
    s(slug="mahila-samarth", short_name="Mahila Samarth", category="women",
      name={"en":"Mahila Samarth Scheme","ta":"மகளிர் சமர்த் திட்டம்","hi":"महिला समर्थ योजना"},
      department={"en":"Ministry of Textiles","ta":"ஜவுளி அமைச்சகம்","hi":"वस्त्र मंत्रालय"},
      description={"en":"Skill training + market linkage for women in textile and handicraft sectors.","ta":"ஜவுளி மற்றும் கைவினைத் துறைகளில் பெண்களுக்கு பயிற்சி + சந்தை இணைப்பு.","hi":"वस्त्र और हस्तशिल्प क्षेत्रों में महिलाओं के लिए प्रशिक्षण + बाजार संपर्क।"},
      min_age=18, max_age=50, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Bank passbook"],
      source_url="https://texmin.nic.in/"),

    s(slug="wep-india", short_name="WEP", category="women",
      name={"en":"Women Entrepreneurship Platform","ta":"பெண் தொழில்முனைவு தளம்","hi":"महिला उद्यमिता मंच"},
      department={"en":"NITI Aayog","ta":"நிதி ஆயோக்","hi":"नीति आयोग"},
      description={"en":"Digital platform for women entrepreneurs — mentorship, funding, networking, and learning.","ta":"பெண் தொழில்முனைவோருக்கான டிஜிட்டல் தளம் — வழிகாட்டுதல், நிதி, நெட்வொர்க்கிங்.","hi":"महिला उद्यमियों के लिए डिजिटल प्लेटफॉर्म — मेंटरशिप, फंडिंग, नेटवर्किंग।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Email"],
      source_url="https://wep.gov.in/"),

    s(slug="sbi-mahila-udyami", short_name="SBI Mahila", category="women",
      name={"en":"SBI Mahila Udyami Yojana","ta":"SBI மகளிர் உத்யமி யோஜனா","hi":"SBI महिला उद्यमी योजना"},
      department={"en":"State Bank of India","ta":"இந்திய ஸ்டேட் வங்கி","hi":"भारतीय स्टेट बैंक"},
      description={"en":"Loans up to ₹50 lakh for women entrepreneurs at concessional rates under Stand-Up India.","ta":"Stand-Up India-யின் கீழ் பெண் தொழில்முனைவோருக்கு ₹50 லட்சம் வரை சலுகை கடன்.","hi":"Stand-Up India के तहत महिला उद्यमियों को ₹50 लाख तक रियायती ऋण।"},
      min_age=18, max_age=60, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new"], education=None,
      max_loan=5000000, interest_rate="Concessional", subsidy_percent=0,
      moratorium="18 months", repayment_years="7 years",
      documents=["Aadhaar Card","PAN Card","Project report","Bank statements"],
      source_url="https://sbi.co.in/"),

    s(slug="dwcra-tn", short_name="DWCRA", category="women",
      name={"en":"DWCRA Self Employment for Women","ta":"DWCRA மகளிர் சுய வேலைவாய்ப்பு","hi":"DWCRA महिला स्वरोजगार"},
      department={"en":"TN Rural Development","ta":"தமிழ்நாடு ஊரக வளர்ச்சி","hi":"तमिलनाडु ग्रामीण विकास"},
      description={"en":"Revolving fund + skill training for rural women's groups to start small businesses.","ta":"ஊரக பெண்கள் குழுக்களுக்கு சுழல் நிதி + பயிற்சி.","hi":"ग्रामीण महिला समूहों को रिवॉल्विंग फंड + प्रशिक्षण।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new"], education=None,
      max_loan=200000, interest_rate="4%", subsidy_percent=25,
      moratorium="6 months", repayment_years="3 years",
      documents=["SHG registration","Aadhaar Card","Bank passbook"],
      source_url="https://www.tnrd.gov.in/"),

    s(slug="wdcw-skill", short_name="WDCW Skill", category="women",
      name={"en":"Women Skill Development Scheme","ta":"மகளிர் திறன் மேம்பாட்டுத் திட்டம்","hi":"महिला कौशल विकास योजना"},
      department={"en":"Ministry of Women & Child Development","ta":"மகளிர் மற்றும் குழந்தை மேம்பாட்டு அமைச்சகம்","hi":"महिला और बाल विकास मंत्रालय"},
      description={"en":"Free skill training for women in beauty, tailoring, IT, and food processing.","ta":"அழகு, தையல், IT, உணவு பதப்படுத்துதல் ஆகியவற்றில் பெண்களுக்கு இலவச பயிற்சி.","hi":"सौंदर्य, टेलरिंग, IT, खाद्य प्रसंस्करण में महिलाओं को मुफ्त प्रशिक्षण।"},
      min_age=18, max_age=45, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Education certificate"],
      source_url="https://wcd.nic.in/"),

    s(slug="tn-women-industrial-estate", short_name="TN Women IE", category="women",
      name={"en":"TN Women Industrial Estate Scheme","ta":"தமிழ்நாடு மகளிர் தொழிற்பேட்டை","hi":"तमिलनाडु महिला औद्योगिक क्षेत्र"},
      department={"en":"TN Industries Department","ta":"தமிழ்நாடு தொழில்துறை","hi":"तमिलनाडु उद्योग विभाग"},
      description={"en":"Dedicated industrial estates in 8 districts for women entrepreneurs with subsidized land.","ta":"8 மாவட்டங்களில் பெண் தொழில்முனைவோருக்கு மானிய நிலத்துடன் தொழிற்பேட்டைகள்.","hi":"8 जिलों में महिला उद्यमियों के लिए सब्सिडी वाली भूमि के साथ औद्योगिक क्षेत्र।"},
      min_age=21, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new"], education=None,
      max_loan=5000000, interest_rate="As per bank", subsidy_percent=25,
      moratorium="12 months", repayment_years="10 years",
      documents=["Aadhaar Card","Business plan","Bank statements"],
      source_url="https://www.investingintn.org/"),

    s(slug="women-startup-tn", short_name="Women Startup", category="startup",
      name={"en":"TN Women Startup Fund","ta":"தமிழ்நாடு மகளிர் ஸ்டார்ட்அப் நிதி","hi":"तमिलनाडु महिला स्टार्टअप फंड"},
      department={"en":"StartupTN, Government of Tamil Nadu","ta":"ஸ்டார்ட்அப் தமிழ்நாடு","hi":"स्टार्टअपTN"},
      description={"en":"Equity funding up to ₹50 lakh for women-led startups registered in Tamil Nadu.","ta":"தமிழ்நாட்டில் பதிவுசெய்யப்பட்ட பெண் ஸ்டார்ட்அப்களுக்கு ₹50 லட்சம் வரை நிதி.","hi":"तमिलनाडु में पंजीकृत महिला स्टार्टअप के लिए ₹50 लाख तक फंडिंग।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new","existing"], education=None,
      max_loan=5000000, interest_rate="Equity", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Startup registration","Pitch deck","Team details"],
      source_url="https://startuptn.in/"),

    s(slug="shg-women-credit", short_name="SHG Women Credit", category="women",
      name={"en":"SHG Women Credit Scheme","ta":"SHG மகளிர் கடன் திட்டம்","hi":"SHG महिला ऋण योजना"},
      department={"en":"NABARD","ta":"நபார்டு","hi":"नाबार्ड"},
      description={"en":"Low-interest credit to women SHGs with limit up to 6x of group corpus.","ta":"மகளிர் SHG-க்கு குழு நிதியின் 6 மடங்கு வரை குறைந்த வட்டி கடன்.","hi":"महिला SHG को समूह कोष का 6 गुना तक कम ब्याज ऋण।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new","existing"], education=None,
      max_loan=1500000, interest_rate="7%", subsidy_percent=0,
      moratorium="3 months", repayment_years="3 years",
      documents=["SHG registration","Bank passbook","Group resolution"],
      source_url="https://www.nabard.org/"),

    s(slug="mahila-e-haat", short_name="Mahila e-Haat", category="women",
      name={"en":"Mahila e-Haat Online Marketplace","ta":"மகளிர் இ-ஹாட் ஆன்லைன் சந்தை","hi":"महिला ई-हाट ऑनलाइन बाज़ार"},
      department={"en":"Ministry of Women & Child Development","ta":"மகளிர் அமைச்சகம்","hi":"महिला मंत्रालय"},
      description={"en":"Online platform for women entrepreneurs to sell products directly to customers.","ta":"பெண் தொழில்முனைவோர் தயாரிப்புகளை நேரடியாக விற்க ஆன்லைன் தளம்.","hi":"महिला उद्यमियों के लिए सीधे ग्राहकों को उत्पाद बेचने का ऑनलाइन प्लेटफॉर्म।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Product photos","Bank details"],
      source_url="https://mahilaehaat-rmk.gov.in/"),

    s(slug="tn-women-shg-federation", short_name="SHG Federation", category="women",
      name={"en":"TN Women SHG Federation Support","ta":"தமிழ்நாடு மகளிர் SHG கூட்டமைப்பு","hi":"तमिलनाडु महिला SHG संघ"},
      department={"en":"TN Rural Development","ta":"தமிழ்நாடு ஊரக வளர்ச்சி","hi":"तमिलनाडु ग्रामीण विकास"},
      description={"en":"Cluster-level federation support for SHG women to scale collective businesses.","ta":"SHG பெண்கள் கூட்டு வணிகங்களை விரிவாக்க கிளஸ்டர் ஆதரவு.","hi":"SHG महिलाओं को सामूहिक व्यवसाय बढ़ाने के लिए क्लस्टर सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["existing"], education=None,
      max_loan=2000000, interest_rate="Concessional", subsidy_percent=30,
      moratorium="6 months", repayment_years="5 years",
      documents=["Federation registration","SHG list","Bank passbook"],
      source_url="https://www.tnrd.gov.in/"),

    # ============================================================
    # Education & Scholarships — 5 schemes
    # ============================================================
    s(slug="inspire-scholarship", short_name="INSPIRE", category="startup",
      name={"en":"INSPIRE Scholarship for Science Students","ta":"INSPIRE அறிவியல் உதவித்தொகை","hi":"INSPIRE विज्ञान छात्रवृत्ति"},
      department={"en":"Department of Science & Technology","ta":"அறிவியல் மற்றும் தொழில்நுட்பத் துறை","hi":"विज्ञान और प्रौद्योगिकी विभाग"},
      description={"en":"Scholarship of ₹80,000/year for top science students to pursue research careers.","ta":"சிறந்த அறிவியல் மாணவர்களுக்கு ஆண்டுக்கு ₹80,000 உதவித்தொகை.","hi":"शीर्ष विज्ञान छात्रों को वार्षिक ₹80,000 छात्रवृत्ति।"},
      min_age=17, max_age=22, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education="12th Pass",
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Marksheet","Admission letter"],
      source_url="https://online-inspire.gov.in/"),

    s(slug="pragati-scholarship", short_name="AICTE Pragati", category="women",
      name={"en":"AICTE Pragati Scholarship for Girls","ta":"AICTE பிரகதி மகளிர் உதவித்தொகை","hi":"AICTE प्रगति छात्रवृत्ति"},
      department={"en":"AICTE, Ministry of Education","ta":"AICTE, கல்வி அமைச்சகம்","hi":"AICTE, शिक्षा मंत्रालय"},
      description={"en":"₹50,000/year scholarship for girls in AICTE-approved technical courses.","ta":"AICTE அங்கீகரிக்கப்பட்ட தொழில்நுட்ப படிப்புகளில் பெண்களுக்கு ₹50,000/ஆண்டு.","hi":"AICTE अनुमोदित तकनीकी पाठ्यक्रमों में लड़कियों को ₹50,000/वर्ष।"},
      min_age=17, max_age=25, max_income=800000, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new"], education="12th Pass",
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Income certificate","Admission letter","Marksheet"],
      source_url="https://scholarships.gov.in/"),

    s(slug="saksham-scholarship", short_name="AICTE Saksham", category="business",
      name={"en":"AICTE Saksham Scholarship for Differently-Abled","ta":"AICTE சக்ஷம் மாற்றுத்திறனாளர் உதவித்தொகை","hi":"AICTE सक्षम दिव्यांग छात्रवृत्ति"},
      department={"en":"AICTE, Ministry of Education","ta":"AICTE, கல்வி அமைச்சகம்","hi":"AICTE, शिक्षा मंत्रालय"},
      description={"en":"₹50,000/year for differently-abled students in AICTE-approved courses.","ta":"AICTE அங்கீகரிக்கப்பட்ட படிப்புகளில் மாற்றுத்திறனாளி மாணவர்களுக்கு ₹50,000/ஆண்டு.","hi":"AICTE अनुमोदित पाठ्यक्रमों में दिव्यांग छात्रों को ₹50,000/वर्ष।"},
      min_age=17, max_age=30, max_income=800000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education="12th Pass",
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Disability certificate","Admission letter"],
      source_url="https://scholarships.gov.in/"),

    s(slug="nisar-scholarship", short_name="NISAR", category="business",
      name={"en":"NISAR Scholarship for Students","ta":"NISAR மாணவர் உதவித்தொகை","hi":"NISAR छात्रवृत्ति"},
      department={"en":"Ministry of Education","ta":"கல்வி அமைச்சகம்","hi":"शिक्षा मंत्रालय"},
      description={"en":"Scholarship for students pursuing graduate/postgraduate programs in India.","ta":"இந்தியாவில் இளங்கலை/முதுகலை படிக்கும் மாணவர்களுக்கு உதவித்தொகை.","hi":"भारत में स्नातक/स्नातकोत्तर कार्यक्रम करने वाले छात्रों के लिए छात्रवृत्ति।"},
      min_age=17, max_age=30, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education="12th Pass",
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Marksheet","Admission letter"],
      source_url="https://scholarships.gov.in/"),

    s(slug="central-sector-scholarship", short_name="CSS", category="business",
      name={"en":"Central Sector Scholarship Scheme","ta":"மத்திய துறை உதவித்தொகை","hi":"केंद्रीय क्षेत्र छात्रवृत्ति"},
      department={"en":"Ministry of Education","ta":"கல்வி அமைச்சகம்","hi":"शिक्षा मंत्रालय"},
      description={"en":"₹10,000–20,000/year for top 20 percentile students in Class 12.","ta":"12-ம் வகுப்பில் முதல் 20 சதவீத மாணவர்களுக்கு ₹10,000–20,000/ஆண்டு.","hi":"कक्षा 12 में शीर्ष 20 प्रतिशत छात्रों को ₹10,000–20,000/वर्ष।"},
      min_age=17, max_age=25, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education="12th Pass",
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Marksheet","Admission letter"],
      source_url="https://scholarships.gov.in/"),

    # ============================================================
    # Health & Insurance — 5 schemes
    # ============================================================
    s(slug="pmjay-senior", short_name="PM-JAY Senior", category="business",
      name={"en":"Ayushman Bharat for Senior Citizens 70+","ta":"70+ மூத்த குடிமக்களுக்கு ஆயுஷ்மான்","hi":"70+ वरिष्ठ नागरिकों के लिए आयुष्मान"},
      department={"en":"Ministry of Health","ta":"சுகாதார அமைச்சகம்","hi":"स्वास्थ्य मंत्रालय"},
      description={"en":"Free health cover of ₹5 lakh/year for all senior citizens above 70 years.","ta":"70 வயதுக்கு மேற்பட்ட அனைத்து மூத்த குடிமக்களுக்கும் ₹5 லட்சம் இலவச மருத்துவ காப்பீடு.","hi":"70 वर्ष से अधिक सभी वरिष्ठ नागरिकों को ₹5 लाख मुफ्त स्वास्थ्य कवर।"},
      min_age=70, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Age proof"],
      source_url="https://pmjay.gov.in/"),

    s(slug="esic-scheme", short_name="ESIC", category="business",
      name={"en":"Employees State Insurance Scheme","ta":"ஊழியர் மாநில காப்பீட்டுத் திட்டம்","hi":"कर्मचारी राज्य बीमा योजना"},
      department={"en":"ESIC, Ministry of Labour","ta":"ESIC, தொழிலாளர் அமைச்சகம்","hi":"ESIC, श्रम मंत्रालय"},
      description={"en":"Health + maternity + disability benefits for workers in registered businesses.","ta":"பதிவுசெய்யப்பட்ட வணிகங்களில் பணிபுரியும் தொழிலாளர்களுக்கு மருத்துவ/மகப்பேறு காப்பீடு.","hi":"पंजीकृत व्यवसायों में कामगारों को स्वास्थ्य/मातृत्व बीमा।"},
      min_age=18, max_age=60, max_income=21000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Employment proof","Bank passbook"],
      source_url="https://www.esic.gov.in/"),

    s(slug="cghs", short_name="CGHS", category="business",
      name={"en":"Central Government Health Scheme","ta":"மத்திய அரசு சுகாதார திட்டம்","hi":"केंद्र सरकार स्वास्थ्य योजना"},
      department={"en":"Ministry of Health","ta":"சுகாதார அமைச்சகம்","hi":"स्वास्थ्य मंत्रालय"},
      description={"en":"Comprehensive healthcare for central government employees and pensioners.","ta":"மத்திய அரசு ஊழியர்கள் மற்றும் ஓய்வூதியதாரர்களுக்கு முழு சுகாதாரம்.","hi":"केंद्र सरकार के कर्मचारियों और पेंशनभोगियों के लिए व्यापक स्वास्थ्य सेवा।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["CGHS card","Aadhaar Card"],
      source_url="https://cghs.gov.in/"),

    s(slug="pm-matru-vandana", short_name="PMMVY", category="women",
      name={"en":"Pradhan Mantri Matru Vandana Yojana","ta":"பிரதம மந்திரி மாத்ரு வந்தனா","hi":"प्रधानमंत्री मातृ वंदना योजना"},
      department={"en":"Ministry of Women & Child Development","ta":"மகளிர் அமைச்சகம்","hi":"महिला मंत्रालय"},
      description={"en":"₹5,000 maternity benefit for first-time mothers and pregnant women.","ta":"முதல் முறை தாய்மார்களுக்கு ₹5,000 மகப்பேறு உதவி.","hi":"पहली बार माताओं को ₹5,000 मातृत्व लाभ।"},
      min_age=18, max_age=45, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new","existing"], education=None,
      max_loan=5000, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","MCP card","Bank passbook"],
      source_url="https://pmmvy.wcd.gov.in/"),

    s(slug="pm-jeevan-jyoti", short_name="PMJJBY", category="business",
      name={"en":"PM Jeevan Jyoti Bima Yojana (Life)","ta":"PM ஜீவன் ஜோதி பீமா (ஆயுள்)","hi":"PM जीवन ज्योति बीमा (जीवन)"},
      department={"en":"Ministry of Finance","ta":"நிதி அமைச்சகம்","hi":"वित्त मंत्रालय"},
      description={"en":"₹2 lakh life insurance at ₹436/year premium for ages 18–50.","ta":"18-50 வயதுக்கு ₹436/ஆண்டு பிரீமியத்தில் ₹2 லட்சம் ஆயுள் காப்பீடு.","hi":"18-50 वर्ष के लिए ₹436/वर्ष पर ₹2 लाख जीवन बीमा।"},
      min_age=18, max_age=50, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=0,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Bank account"],
      source_url="https://www.jansuraksha.gov.in/"),

    # ============================================================
    # Agriculture & Rural — 5 schemes
    # ============================================================
    s(slug="pm-kusum", short_name="PM-KUSUM", category="agriculture",
      name={"en":"PM Kisan Urja Suraksha evam Utthaan Mahabhiyan","ta":"PM கிசான் உர்ஜா சுரக்ஷா","hi":"पीएम किसान ऊर्जा सुरक्षा"},
      department={"en":"Ministry of New & Renewable Energy","ta":"புதிய மற்றும் புதுப்பிக்கத்தக்க எரிசக்தி அமைச்சகம்","hi":"नवीन और नवीकरणीय ऊर्जा मंत्रालय"},
      description={"en":"Solar pump + solar power plant subsidies up to 60% for farmers.","ta":"விவசாயிகளுக்கு சூரிய மின் குழாய் + சூரிய மின் நிலைய மானியம் 60% வரை.","hi":"किसानों को सोलर पंप + सोलर पावर प्लांट सब्सिडी 60% तक।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=1000000, interest_rate="As per bank", subsidy_percent=60,
      moratorium="6 months", repayment_years="5 – 7 years",
      documents=["Aadhaar Card","Land documents","Electricity bill"],
      source_url="https://pmkusum.mnre.gov.in/"),

    s(slug="enam-trade", short_name="e-NAM Trade", category="agriculture",
      name={"en":"e-NAM Online Agri Trading","ta":"e-NAM ஆன்லைன் வேளாண் வணிகம்","hi":"e-NAM ऑनलाइन कृषि व्यापार"},
      department={"en":"Ministry of Agriculture","ta":"வேளாண்மை அமைச்சகம்","hi":"कृषि मंत्रालय"},
      description={"en":"Online trading platform for farmers to sell produce directly to buyers.","ta":"விவசாயிகள் நேரடியாக வாங்குபவர்களுக்கு விற்க ஆன்லைன் தளம்.","hi":"किसानों को सीधे खरीदारों को बेचने का ऑनलाइन प्लेटफॉर्म।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=0,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Land records","Bank account"],
      source_url="https://www.enam.gov.in/"),

    s(slug="pkvy-organic", short_name="PKVY Organic", category="agriculture",
      name={"en":"Paramparagat Krishi Vikas Yojana (Organic)","ta":"பாரம்பரிய வேளாண் விகாஸ் (இயற்கை)","hi":"परंपरागत कृषि विकास (जैविक)"},
      department={"en":"Ministry of Agriculture","ta":"வேளாண்மை அமைச்சகம்","hi":"कृषि मंत्रालय"},
      description={"en":"₹50,000/hectare support for organic farming over 3 years with certification.","ta":"3 ஆண்டுகளில் இயற்கை வேளாண்மைக்கு ஹெக்டேருக்கு ₹50,000 ஆதரவு.","hi":"3 वर्षों में जैविक खेती के लिए ₹50,000/हेक्टेयर सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=500000, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Land documents","Cluster proposal"],
      source_url="https://pgsindia-ncof.gov.in/"),

    s(slug="rkvy-tn", short_name="RKVY", category="agriculture",
      name={"en":"Rashtriya Krishi Vikas Yojana","ta":"ராஷ்ட்ரிய கிருஷி விகாஸ் யோஜனா","hi":"राष्ट्रीय कृषि विकास योजना"},
      department={"en":"Ministry of Agriculture","ta":"வேளாண்மை அமைச்சகம்","hi":"कृषि मंत्रालय"},
      description={"en":"State-level agriculture development projects with funding for infrastructure and inputs.","ta":"மாநில அளவில் வேளாண் உள்கட்டமைப்பு மேம்பாட்டு திட்டங்கள்.","hi":"राज्य स्तरीय कृषि अवसंरचना विकास परियोजनाएँ।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=2000000, interest_rate="Concessional", subsidy_percent=50,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Land documents","Project report"],
      source_url="https://rkvy.da.gov.in/"),

    s(slug="aif-agri", short_name="AIF", category="agriculture",
      name={"en":"Agriculture Infrastructure Fund","ta":"வேளாண் உள்கட்டமைப்பு நிதி","hi":"कृषि अवसंरचना कोष"},
      department={"en":"Ministry of Agriculture","ta":"வேளாண்மை அமைச்சகம்","hi":"कृषि मंत्रालय"},
      description={"en":"3% interest subvention on loans up to ₹2 crore for post-harvest infrastructure.","ta":"அறுவடைக்குப் பின் உள்கட்டமைப்புக்கு ₹2 கோடி வரை 3% வட்டி மானியம்.","hi":"कटाई के बाद की अवसंरचना के लिए ₹2 करोड़ तक 3% ब्याज सब्सिडी।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=20000000, interest_rate="9% (with 3% subsidy)", subsidy_percent=3,
      moratorium="6 – 12 months", repayment_years="7 years",
      documents=["Aadhaar Card","Land documents","Project report","Bank statements"],
      source_url="https://agriinfra.dac.gov.in/"),
]


def run():
    db = SessionLocal()
    added, skipped = 0, 0
    try:
        for s_data in SCHEMES:
            existing = db.query(Scheme).filter(Scheme.slug == s_data["slug"]).first()
            if existing:
                skipped += 1
                continue
            db.add(Scheme(**s_data))
            added += 1
        db.commit()
        total = db.query(Scheme).count()
        print(f"[OK] Added: {added}, Skipped: {skipped}")
        print(f"[OK] Total schemes in DB: {total}")
    finally:
        db.close()


if __name__ == "__main__":
    run()