"""Seed all remaining schemes (batches 4-11) to reach 100 total.

Usage:  python -m scripts.seed_all
Idempotent: existing slugs are skipped.
"""
from datetime import date
from app.database import SessionLocal
from app.models.scheme import Scheme

V = date(2026, 9, 16)
BY = "Admin User"
CATS = ["General", "OBC", "BC", "MBC", "SC", "ST"]

def s(**kw):
    kw.setdefault("status", "active")
    kw.setdefault("verified_by", BY)
    kw.setdefault("last_verified", V)
    return kw

SCHEMES = [
    # ============================================================
    # BATCH 4 — Startup / Agriculture / Handicraft (10)
    # ============================================================
    s(slug="startup-india-seed-fund", short_name="SISFS", category="startup",
      name={"en":"Startup India Seed Fund Scheme","ta":"ஸ்டார்ட்அப் இந்தியா விதை நிதி","hi":"स्टार्टअप इंडिया सीड फंड"},
      department={"en":"DPIIT, Ministry of Commerce","ta":"DPIIT, வர்த்தக அமைச்சகம்","hi":"DPIIT, वाणिज्य मंत्रालय"},
      description={"en":"Up to ₹50 lakh to startups for proof of concept, prototype, trials and commercialization.","ta":"ஸ்டார்ட்அப்களுக்கு ₹50 லட்சம் வரை நிதி.","hi":"स्टार्टअप को ₹50 लाख तक सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education=None,
      max_loan=5000000, interest_rate="Grant / Equity", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","DPIIT registration","Pitch deck","Incubator recommendation"],
      source_url="https://seedfund.startupindia.gov.in/"),

    s(slug="nidhi-prayas", short_name="NIDHI Prayas", category="startup",
      name={"en":"NIDHI Prayas — Seed Support","ta":"நிதி பிரயாஸ் விதை ஆதரவு","hi":"निधि प्रयास सीड सपोर्ट"},
      department={"en":"DST, Govt of India","ta":"DST, இந்திய அரசு","hi":"DST, भारत सरकार"},
      description={"en":"Up to ₹10 lakh grant for innovators to build prototypes and validate products.","ta":"முன்மாதிரி உருவாக்க ₹10 லட்சம் வரை நிதி.","hi":"प्रोटोटाइप के लिए ₹10 लाख तक अनुदान।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education=None,
      max_loan=1000000, interest_rate="Grant", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Proof of innovation","Prototype document"],
      source_url="https://nidhi.dst.gov.in/"),

    s(slug="national-beekeeping", short_name="NBHM", category="agriculture",
      name={"en":"National Beekeeping and Honey Mission","ta":"தேசிய தேனீ வளர்ப்பு இயக்கம்","hi":"राष्ट्रीय मधुमक्खी पालन मिशन"},
      department={"en":"Ministry of Agriculture","ta":"வேளாண்மை அமைச்சகம்","hi":"कृषि मंत्रालय"},
      description={"en":"Assistance for beekeeping, honey processing units and bee colony management.","ta":"தேனீ வளர்ப்பு மற்றும் தேன் பதப்படுத்துதலுக்கு உதவி.","hi":"मधुमक्खी पालन और शहद प्रसंस्करण के लिए सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=500000, interest_rate="As per bank", subsidy_percent=50,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Project proposal","Bank details"],
      source_url="https://nbb.gov.in/"),

    s(slug="agri-clinics", short_name="ACABC", category="agriculture",
      name={"en":"Agri Clinics and Agri Business Centres","ta":"வேளாண் கிளினிக்குகள் & வணிக மையங்கள்","hi":"कृषि क्लिनिक और कृषि व्यवसाय केंद्र"},
      department={"en":"Ministry of Agriculture","ta":"வேளாண்மை அமைச்சகம்","hi":"कृषि मंत्रालय"},
      description={"en":"Supports agriculture graduates to set up agri-clinics and agri-business centres.","ta":"வேளாண்மை பட்டதாரிகளுக்கு கிளினிக்குகள் அமைக்க ஆதரவு.","hi":"कृषि स्नातकों को क्लिनिक स्थापित करने के लिए सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"],
      education="Bachelor's in Agriculture",
      max_loan=2000000, interest_rate="As per bank", subsidy_percent=44,
      moratorium="12 months", repayment_years="5 – 10 years",
      documents=["Aadhaar Card","Degree certificate","Project report"],
      source_url="https://www.agriinfra.dac.gov.in/"),

    s(slug="coir-udyami", short_name="Coir Udyami", category="handicraft",
      name={"en":"Coir Udyami Yojana","ta":"கயிறு உத்யமி திட்டம்","hi":"कॉयर उद्यमी योजना"},
      department={"en":"Coir Board, Ministry of MSME","ta":"கயிறு வாரியம்","hi":"कॉयर बोर्ड"},
      description={"en":"40% margin money subsidy for coir processing units (max ₹10 lakh).","ta":"கயிறு பதப்படுத்தும் அலகுகளுக்கு 40% மானியம்.","hi":"कॉयर प्रसंस्करण इकाइयों के लिए 40% सब्सिडी।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education=None,
      max_loan=2500000, interest_rate="As per bank", subsidy_percent=40,
      moratorium="6 months", repayment_years="7 years",
      documents=["Aadhaar Card","Project report","Quotations"],
      source_url="https://coirboard.gov.in/"),

    s(slug="tnrtp", short_name="TNRTP", category="business",
      name={"en":"Tamil Nadu Rural Transformation Project","ta":"தமிழ்நாடு ஊரக மாற்றம் திட்டம்","hi":"तमिलनाडु ग्रामीण परिवर्तन परियोजना"},
      department={"en":"TN Rural Development + World Bank","ta":"தமிழ்நாடு ஊரக வளர்ச்சி","hi":"तमिलनाडु ग्रामीण विकास"},
      description={"en":"Enterprise development for rural entrepreneurs in 16 TN blocks.","ta":"16 வட்டாரங்களில் ஊரக தொழில்முனைவோருக்கு ஆதரவு.","hi":"16 ब्लॉकों में ग्रामीण उद्यमियों के लिए सहायता।"},
      min_age=18, max_age=60, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=1000000, interest_rate="Concessional", subsidy_percent=25,
      moratorium="6 months", repayment_years="3 – 5 years",
      documents=["Aadhaar Card","Ration Card","Business proposal"],
      source_url="https://www.tnrtp.org/"),

    s(slug="pmmsy", short_name="PMMSY", category="agriculture",
      name={"en":"Pradhan Mantri Matsya Sampada Yojana","ta":"பிரதம மந்திரி மத்ஸ்ய சம்பதா","hi":"प्रधानमंत्री मत्स्य संपदा योजना"},
      department={"en":"Ministry of Fisheries","ta":"மீன்வள அமைச்சகம்","hi":"मत्स्य मंत्रालय"},
      description={"en":"Assistance for fish farmers with 40-60% subsidy based on category.","ta":"மீனவர்களுக்கு 40-60% மானியம்.","hi":"मछुआरों को 40-60% सब्सिडी।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=3000000, interest_rate="As per bank", subsidy_percent=60,
      moratorium="6 – 12 months", repayment_years="5 – 7 years",
      documents=["Aadhaar Card","Project report","Fisheries ID"],
      source_url="https://pmmsy.dof.gov.in/"),

    s(slug="nhdp-handloom", short_name="NHDP", category="handicraft",
      name={"en":"National Handloom Development Programme","ta":"தேசிய கைத்தறி மேம்பாட்டுத் திட்டம்","hi":"राष्ट्रीय हथकरघा विकास कार्यक्रम"},
      department={"en":"Ministry of Textiles","ta":"ஜவுளி அமைச்சகம்","hi":"वस्त्र मंत्रालय"},
      description={"en":"Support to handloom weavers — looms, design, marketing, credit.","ta":"கைத்தறி நெசவாளர்களுக்கு ஆதரவு.","hi":"हथकरघा बुनकरों को सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=2000000, interest_rate="6% concessional", subsidy_percent=30,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Weaver ID card","Bank passbook"],
      source_url="https://handlooms.nic.in/"),

    s(slug="nssh", short_name="NSSH", category="sc_st",
      name={"en":"National SC-ST Hub Scheme","ta":"தேசிய SC-ST மைய திட்டம்","hi":"राष्ट्रीय SC-ST हब"},
      department={"en":"Ministry of MSME","ta":"MSME அமைச்சகம்","hi":"MSME मंत्रालय"},
      description={"en":"Capacity building for SC/ST entrepreneurs; 4% procurement mandate support.","ta":"SC/ST தொழில்முனைவோருக்கு திறன் மேம்பாடு.","hi":"SC/ST उद्यमियों के लिए क्षमता निर्माण।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=["SC","ST"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Caste certificate","Udyam Registration"],
      source_url="https://www.scsthub.in/"),

    s(slug="ambedkar-innovation", short_name="ASIIM", category="sc_st",
      name={"en":"Ambedkar Social Innovation Mission","ta":"அம்பேத்கர் சமூக புதுமை இயக்கம்","hi":"अम्बेडकर सामाजिक नवाचार मिशन"},
      department={"en":"Ministry of Social Justice","ta":"சமூக நீதி அமைச்சகம்","hi":"सामाजिक न्याय मंत्रालय"},
      description={"en":"Equity funding up to ₹30 lakh to SC/ST startups via incubators.","ta":"SC/ST ஸ்டார்ட்அப்களுக்கு ₹30 லட்சம் வரை நிதி.","hi":"SC/ST स्टार्टअप को ₹30 लाख तक फंडिंग।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=["SC","ST"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=3000000, interest_rate="Equity", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Caste certificate","Pitch deck"],
      source_url="https://socialjustice.gov.in/"),

    # ============================================================
    # BATCH 5 — MSME / Business support (10)
    # ============================================================
    s(slug="zed-certification", short_name="ZED", category="business",
      name={"en":"Zero Defect Zero Effect Certification","ta":"ஜீரோ டிஃபெக்ட் ஜீரோ எஃபெக்ட்","hi":"जीरो डिफेक्ट जीरो इफेक्ट"},
      department={"en":"Ministry of MSME","ta":"MSME அமைச்சகம்","hi":"MSME मंत्रालय"},
      description={"en":"Subsidy for MSMEs to obtain ZED certification for quality and environmental standards.","ta":"தரம் மற்றும் சுற்றுச்சூழலுக்கான ZED சான்றிதழ் மானியம்.","hi":"गुणवत्ता और पर्यावरण मानकों के लिए ZED प्रमाणन सब्सिडी।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=80,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Udyam Registration","GST"],
      source_url="https://zed.msme.gov.in/"),

    s(slug="lean-manufacturing", short_name="LMC", category="business",
      name={"en":"Lean Manufacturing Competitiveness Scheme","ta":"லீன் உற்பத்தி போட்டித்திறன்","hi":"लीन मैन्युफैक्चरिंग प्रतिस्पर्धात्मकता"},
      department={"en":"Ministry of MSME","ta":"MSME அமைச்சகம்","hi":"MSME मंत्रालय"},
      description={"en":"Subsidy for MSMEs to adopt lean manufacturing techniques via cluster approach.","ta":"கிளஸ்டர் அணுகுமுறையில் லீன் உற்பத்தி நுட்பங்களை ஏற்க மானியம்.","hi":"क्लस्टर दृष्टिकोण से लीन मैन्युफैक्चरिंग अपनाने के लिए सब्सिडी।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=1000000, interest_rate="As per bank", subsidy_percent=80,
      moratorium="6 months", repayment_years="3 years",
      documents=["Aadhaar Card","Udyam Registration","Cluster proposal"],
      source_url="https://www.msme.gov.in/"),

    s(slug="design-clinic", short_name="Design Clinic", category="business",
      name={"en":"Design Clinic Scheme for MSMEs","ta":"MSME வடிவமைப்பு கிளினிக்","hi":"MSME डिज़ाइन क्लिनिक"},
      department={"en":"Ministry of MSME","ta":"MSME அமைச்சகம்","hi":"MSME मंत्रालय"},
      description={"en":"Financial support up to ₹15 lakh for design projects in MSMEs.","ta":"MSME வடிவமைப்பு திட்டங்களுக்கு ₹15 லட்சம் வரை ஆதரவு.","hi":"MSME डिज़ाइन परियोजनाओं के लिए ₹15 लाख तक सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=1500000, interest_rate="Grant", subsidy_percent=75,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Udyam Registration","Design project report"],
      source_url="https://designclinicsmsme.org/"),

    s(slug="ipr-facilitation", short_name="IPR", category="business",
      name={"en":"IPR Facilitation Scheme","ta":"IPR வசதி திட்டம்","hi":"IPR सुविधा योजना"},
      department={"en":"Ministry of MSME","ta":"MSME அமைச்சகம்","hi":"MSME मंत्रालय"},
      description={"en":"Reimbursement of patent/trademark filing costs for MSMEs.","ta":"MSME-க்கு காப்புரிமை/வணிகக்குறி பதிவு செலவு திருப்பிச் செலுத்தல்.","hi":"MSME के लिए पेटेंट/ट्रेडमार्क फाइलिंग लागत की प्रतिपूर्ति।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Udyam Registration","Patent application"],
      source_url="https://ipr.msme.gov.in/"),

    s(slug="digital-msme", short_name="Digital MSME", category="business",
      name={"en":"Digital MSME Scheme","ta":"டிஜிட்டல் MSME திட்டம்","hi":"डिजिटल MSME योजना"},
      department={"en":"Ministry of MSME","ta":"MSME அமைச்சகம்","hi":"MSME मंत्रालय"},
      description={"en":"Subsidy for MSMEs to adopt cloud computing and digital tools.","ta":"கிளவுட் கம்ப்யூட்டிங் மற்றும் டிஜிட்டல் கருவிகளை ஏற்க மானியம்.","hi":"क्लाउड कंप्यूटिंग और डिजिटल उपकरण अपनाने के लिए सब्सिडी।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=1000000, interest_rate="As per bank", subsidy_percent=50,
      moratorium=None, repayment_years="3 years",
      documents=["Aadhaar Card","Udyam Registration","IT project plan"],
      source_url="https://www.digitalmsme.gov.in/"),

    s(slug="msme-champions", short_name="Champions", category="business",
      name={"en":"MSME Champions Scheme","ta":"MSME சாம்பியன்ஸ்","hi":"MSME चैंपियंस"},
      department={"en":"Ministry of MSME","ta":"MSME அமைச்சகம்","hi":"MSME मंत्रालय"},
      description={"en":"Umbrella scheme combining Lean, Design, ZED, IPR and Digital initiatives.","ta":"லீன், வடிவமைப்பு, ZED, IPR, டிஜிட்டல் ஆகியவற்றை இணைக்கும் திட்டம்.","hi":"लीन, डिज़ाइन, ZED, IPR, डिजिटल को जोड़ने वाली छत्र योजना।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=2000000, interest_rate="As per bank", subsidy_percent=75,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Udyam Registration","Project proposal"],
      source_url="https://champions.gov.in/"),

    s(slug="procurement-policy", short_name="PPP-MII", category="business",
      name={"en":"Public Procurement (Preference to Make in India)","ta":"பொது கொள்முதல் — இந்தியாவில் தயாரிப்பு","hi":"सार्वजनिक खरीद — मेक इन इंडिया"},
      department={"en":"DPIIT","ta":"DPIIT","hi":"DPIIT"},
      description={"en":"Preference to local suppliers in government procurement with 25%+ local content.","ta":"25%+ உள்ளூர் உள்ளடக்கத்துடன் உள்நாட்டு சப்ளையர்களுக்கு முன்னுரிமை.","hi":"25%+ स्थानीय सामग्री के साथ स्थानीय आपूर्तिकर्ताओं को प्राथमिकता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=0,
      moratorium=None, repayment_years=None,
      documents=["Udyam Registration","Local content certificate"],
      source_url="https://dpiit.gov.in/"),

    s(slug="technology-centre", short_name="TC", category="business",
      name={"en":"Technology Centre Systems Programme","ta":"தொழில்நுட்ப மைய அமைப்பு","hi":"प्रौद्योगिकी केंद्र प्रणाली"},
      department={"en":"Ministry of MSME","ta":"MSME அமைச்சகம்","hi":"MSME मंत्रालय"},
      description={"en":"Access to common facility centres for MSMEs — tooling, testing, training.","ta":"MSME-க்கு பொது வசதி மையங்கள் — கருவி, சோதனை, பயிற்சி.","hi":"MSME के लिए सामान्य सुविधा केंद्र — टूलिंग, परीक्षण, प्रशिक्षण।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=0,
      moratorium=None, repayment_years=None,
      documents=["Udyam Registration","Requirement note"],
      source_url="https://www.msme.gov.in/"),

    s(slug="msme-udyam-assist", short_name="Udyam Assist", category="business",
      name={"en":"Udyam Assist Platform","ta":"உத்யம் உதவி தளம்","hi":"उद्यम सहायता मंच"},
      department={"en":"Ministry of MSME","ta":"MSME அமைச்சகம்","hi":"MSME मंत्रालय"},
      description={"en":"Free Udyam registration and access to benefits for informal micro enterprises.","ta":"முறைசாரா நுண் நிறுவனங்களுக்கு இலவச உத்யம் பதிவு.","hi":"अनौपचारिक सूक्ष्म उद्यमों के लिए मुफ्त उद्यम पंजीकरण।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=0,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Bank account"],
      source_url="https://udyamregistration.gov.in/"),

    s(slug="champion-services-sector", short_name="CSSC", category="business",
      name={"en":"Scheme for Champion Services Sector","ta":"சாம்பியன் சேவைத் துறை திட்டம்","hi":"चैंपियन सेवा क्षेत्र योजना"},
      department={"en":"DPIIT","ta":"DPIIT","hi":"DPIIT"},
      description={"en":"Support for 12 champion service sectors — IT, tourism, logistics, etc.","ta":"12 சாம்பியன் சேவைத் துறைகளுக்கு ஆதரவு.","hi":"12 चैंपियन सेवा क्षेत्रों के लिए सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=10000000, interest_rate="As per bank", subsidy_percent=25,
      moratorium="12 months", repayment_years="5 years",
      documents=["Aadhaar Card","Company registration","Project report"],
      source_url="https://dpiit.gov.in/"),

    # ============================================================
    # BATCH 6 — Women-focused schemes (10)
    # ============================================================
    s(slug="mahila-udyam-nidhi", short_name="MUN", category="women",
      name={"en":"Mahila Udyam Nidhi","ta":"மகளிர் உத்யம் நிதி","hi":"महिला उद्यम निधि"},
      department={"en":"SIDBI","ta":"SIDBI","hi":"SIDBI"},
      description={"en":"Soft loan up to ₹10 lakh for women entrepreneurs to set up small businesses.","ta":"பெண் தொழில்முனைவோருக்கு ₹10 லட்சம் வரை மென்மையான கடன்.","hi":"महिला उद्यमियों को ₹10 लाख तक सॉफ्ट लोन।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new"], education=None,
      max_loan=1000000, interest_rate="10% – 12%", subsidy_percent=0,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Business plan","Bank statements"],
      source_url="https://www.sidbi.in/"),

    s(slug="stree-shakti", short_name="Stree Shakti", category="women",
      name={"en":"Stree Shakti Package","ta":"ஸ்திரீ சக்தி தொகுப்பு","hi":"स्त्री शक्ति पैकेज"},
      department={"en":"State Bank of India","ta":"இந்திய ஸ்டேட் வங்கி","hi":"भारतीय स्टेट बैंक"},
      description={"en":"Concessional loan for women entrepreneurs with 0.5% interest concession on loans above ₹2 lakh.","ta":"பெண் தொழில்முனைவோருக்கு 0.5% வட்டி சலுகை.","hi":"महिला उद्यमियों के लिए 0.5% ब्याज छूट।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new","existing"], education=None,
      max_loan=2000000, interest_rate="Concessional", subsidy_percent=0,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","PAN","Business plan"],
      source_url="https://sbi.co.in/"),

    s(slug="bmb-loan", short_name="BMB", category="women",
      name={"en":"Bharatiya Mahila Bank Loan","ta":"பாரதிய மகளிர் வங்கி கடன்","hi":"भारतीय महिला बैंक ऋण"},
      department={"en":"Bharatiya Mahila Bank / SBI","ta":"பாரதிய மகளிர் வங்கி","hi":"भारतीय महिला बैंक"},
      description={"en":"Loans to women entrepreneurs at concessional rates for small business setup.","ta":"பெண் தொழில்முனைவோருக்கு சலுகை வட்டியில் கடன்.","hi":"महिला उद्यमियों को रियायती दर पर ऋण।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new","existing"], education=None,
      max_loan=2000000, interest_rate="Concessional", subsidy_percent=0,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","PAN","Business details"],
      source_url="https://sbi.co.in/"),

    s(slug="mahila-samridhi", short_name="MSY", category="women",
      name={"en":"Mahila Samridhi Yojana","ta":"மகளிர் சம்ரிதி திட்டம்","hi":"महिला समृद्धि योजना"},
      department={"en":"Ministry of Social Justice","ta":"சமூக நீதி அமைச்சகம்","hi":"सामाजिक न्याय मंत्रालय"},
      description={"en":"Micro-credit to women in backward classes through NHFDC for small businesses.","ta":"பின்தங்கிய வகுப்பு பெண்களுக்கு நுண் கடன்.","hi":"पिछड़े वर्ग की महिलाओं को माइक्रो-क्रेडिट।"},
      min_age=18, max_age=55, max_income=100000, eligible_categories=["OBC","BC","MBC"],
      eligible_genders=["female"], eligible_business_status=["new"], education=None,
      max_loan=100000, interest_rate="6%", subsidy_percent=0,
      moratorium="6 months", repayment_years="3 years",
      documents=["Aadhaar Card","Caste certificate","Income certificate"],
      source_url="https://www.nhfdc.nic.in/"),

    s(slug="annapurna-yojana", short_name="Annapurna", category="women",
      name={"en":"Annapurna Yojana","ta":"அன்னபூர்ணா திட்டம்","hi":"अन्नपूर्णा योजना"},
      department={"en":"Ministry of Food Processing","ta":"உணவு பதப்படுத்தும் அமைச்சகம்","hi":"खाद्य प्रसंस्करण मंत्रालय"},
      description={"en":"Loan up to ₹50,000 to women for setting up food catering units.","ta":"உணவு சேவை அலகுகள் அமைக்க ₹50,000 வரை கடன்.","hi":"खानपान इकाइयाँ स्थापित करने के लिए ₹50,000 तक ऋण।"},
      min_age=18, max_age=60, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new"], education=None,
      max_loan=50000, interest_rate="As per bank", subsidy_percent=0,
      moratorium="3 months", repayment_years="3 years",
      documents=["Aadhaar Card","Ration Card","Business plan"],
      source_url="https://www.nabard.org/"),

    s(slug="wep-tn", short_name="WEP", category="women",
      name={"en":"Women Entrepreneurship Programme - TN","ta":"பெண் தொழில்முனைவு திட்டம் - தமிழ்நாடு","hi":"महिला उद्यमिता कार्यक्रम - तमिलनाडु"},
      department={"en":"TN Corporation for Development of Women","ta":"தமிழ்நாடு மகளிர் மேம்பாட்டு கழகம்","hi":"तमिलनाडु महिला विकास निगम"},
      description={"en":"Training, credit and market linkage for women entrepreneurs in Tamil Nadu.","ta":"தமிழ்நாட்டில் பெண் தொழில்முனைவோருக்கு பயிற்சி, கடன், சந்தை இணைப்பு.","hi":"तमिलनाडु में महिला उद्यमियों के लिए प्रशिक्षण, ऋण, बाजार संपर्क।"},
      min_age=18, max_age=55, max_income=300000, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new","existing"], education=None,
      max_loan=500000, interest_rate="4% – 12%", subsidy_percent=25,
      moratorium="3 – 6 months", repayment_years="2 – 5 years",
      documents=["Aadhaar Card","SHG membership","Income certificate"],
      source_url="https://www.tncdw.tn.gov.in/"),

    s(slug="shg-bank-linkage", short_name="SHG-BL", category="women",
      name={"en":"SHG-Bank Linkage Programme","ta":"சுய உதவிக்குழு வங்கி இணைப்பு","hi":"SHG-बैंक लिंकेज कार्यक्रम"},
      department={"en":"NABARD","ta":"நபார்டு","hi":"नाबार्ड"},
      description={"en":"Credit to women's self-help groups at concessional rates for income generation.","ta":"பெண் சுய உதவிக்குழுக்களுக்கு வருமான உருவாக்கத்திற்கு சலுகை கடன்.","hi":"महिला स्वयं सहायता समूहों को आय सृजन के लिए रियायती ऋण।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new","existing"], education=None,
      max_loan=1500000, interest_rate="7% – 12%", subsidy_percent=0,
      moratorium="3 – 6 months", repayment_years="3 – 5 years",
      documents=["SHG registration","Members list","Bank passbook"],
      source_url="https://www.nabard.org/"),

    s(slug="kudumbashree-tn", short_name="Kudumbashree", category="women",
      name={"en":"Kudumbashree Model - TN","ta":"குடும்பஸ்ரீ மாதிரி - தமிழ்நாடு","hi":"कुडुम्बश्री मॉडल - तमिलनाडु"},
      department={"en":"TN Rural Development","ta":"தமிழ்நாடு ஊரக வளர்ச்சி","hi":"तमिलनाडु ग्रामीण विकास"},
      description={"en":"Neighbourhood group based enterprise support for rural women in TN.","ta":"ஊரக பெண்களுக்கு அண்டை குழு அடிப்படையிலான நிறுவன ஆதரவு.","hi":"ग्रामीण महिलाओं के लिए पड़ोस समूह आधारित उद्यम सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new","existing"], education=None,
      max_loan=500000, interest_rate="Concessional", subsidy_percent=25,
      moratorium="3 months", repayment_years="3 years",
      documents=["SHG membership","Aadhaar Card","Bank passbook"],
      source_url="https://www.tnrd.gov.in/"),

    s(slug="pmay-women", short_name="PMAY-W", category="women",
      name={"en":"PMAY - Women Beneficiary Preference","ta":"PMAY - பெண் பயனாளி முன்னுரிமை","hi":"PMAY - महिला लाभार्थी प्राथमिकता"},
      department={"en":"Ministry of Housing","ta":"வீட்டுவசதி அமைச்சகம்","hi":"आवास मंत्रालय"},
      description={"en":"Home loans with interest subsidy and preference to women ownership in PMAY.","ta":"PMAY-யில் பெண் உரிமைக்கு முன்னுரிமை மற்றும் வட்டி மானியம்.","hi":"PMAY में महिला स्वामित्व को प्राथमिकता और ब्याज सब्सिडी।"},
      min_age=21, max_age=None, max_income=1800000, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new","existing"], education=None,
      max_loan=1200000, interest_rate="6.5% – 8.5%", subsidy_percent=6,
      moratorium=None, repayment_years="20 years",
      documents=["Aadhaar Card","Income certificate","Property documents"],
      source_url="https://pmaymis.gov.in/"),

    s(slug="dwcua", short_name="DWCUA", category="women",
      name={"en":"Development of Women & Children in Urban Areas","ta":"நகர்ப்புற பெண் & குழந்தைகள் மேம்பாடு","hi":"शहरी क्षेत्रों में महिला व बाल विकास"},
      department={"en":"Ministry of Housing & Urban Affairs","ta":"வீட்டுவசதி & நகர்ப்புற விவகாரங்கள்","hi":"आवास और शहरी मामलों के मंत्रालय"},
      description={"en":"Group enterprise support for urban poor women with credit and training.","ta":"நகர்ப்புற ஏழைப் பெண்களுக்கு குழு நிறுவன ஆதரவு.","hi":"शहरी गरीब महिलाओं के लिए समूह उद्यम सहायता।"},
      min_age=18, max_age=60, max_income=None, eligible_categories=CATS,
      eligible_genders=["female"], eligible_business_status=["new"], education=None,
      max_loan=500000, interest_rate="Concessional", subsidy_percent=50,
      moratorium="6 months", repayment_years="3 – 5 years",
      documents=["SHG registration","Aadhaar Card"],
      source_url="https://mohua.gov.in/"),

    # ============================================================
    # BATCH 7 — SC/ST & Social Justice (10)
    # ============================================================
    s(slug="nsfdc-loan", short_name="NSFDC", category="sc_st",
      name={"en":"NSFDC Loan Scheme","ta":"NSFDC கடன் திட்டம்","hi":"NSFDC ऋण योजना"},
      department={"en":"National Scheduled Castes Finance & Development Corp","ta":"தேசிய ஆதிதிராவிடர் நிதிக் கழகம்","hi":"राष्ट्रीय अनुसूचित जाति वित्त निगम"},
      description={"en":"Concessional loans up to ₹30 lakh for SC entrepreneurs to set up businesses.","ta":"SC தொழில்முனைவோருக்கு ₹30 லட்சம் வரை சலுகை கடன்.","hi":"SC उद्यमियों को ₹30 लाख तक रियायती ऋण।"},
      min_age=18, max_age=55, max_income=300000, eligible_categories=["SC"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=3000000, interest_rate="4% – 8%", subsidy_percent=0,
      moratorium="6 months", repayment_years="10 years",
      documents=["Aadhaar Card","Caste certificate","Income certificate","Project report"],
      source_url="https://nsfdc.nic.in/"),

    s(slug="nsbkfdc", short_name="NSKFDC", category="sc_st",
      name={"en":"NSKFDC Loan for Safai Karamcharis","ta":"சஃபாய் கரம்சாரிகளுக்கு NSKFDC கடன்","hi":"सफाई कर्मचारियों के लिए NSKFDC ऋण"},
      department={"en":"National Safai Karamcharis Finance & Dev Corp","ta":"தேசிய சஃபாய் கரம்சாரி நிதிக் கழகம்","hi":"राष्ट्रीय सफाई कर्मचारी वित्त निगम"},
      description={"en":"Concessional loans for safai karamcharis and their dependents for self-employment.","ta":"சஃபாய் கரம்சாரிகள் மற்றும் அவர்களின் சார்ந்தோருக்கு சலுகை கடன்.","hi":"सफाई कर्मचारियों और उनके आश्रितों के लिए रियायती ऋण।"},
      min_age=18, max_age=55, max_income=300000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education=None,
      max_loan=1500000, interest_rate="4% – 8%", subsidy_percent=0,
      moratorium="6 months", repayment_years="10 years",
      documents=["Aadhaar Card","Safai Karamchari certificate","Income certificate"],
      source_url="https://nskfdc.nic.in/"),

    s(slug="van-bandhu", short_name="VBKY", category="sc_st",
      name={"en":"Van Bandhu Kalyan Yojana","ta":"வன் பந்து கல்யாண் யோஜனா","hi":"वन बंधु कल्याण योजना"},
      department={"en":"Ministry of Tribal Affairs","ta":"பழங்குடியினர் அமைச்சகம்","hi":"जनजातीय मामलों का मंत्रालय"},
      description={"en":"Holistic development of tribal communities through livelihood, health, education.","ta":"பழங்குடி சமூகங்களின் முழுமையான மேம்பாடு.","hi":"जनजातीय समुदायों का समग्र विकास।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=["ST"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=500000, interest_rate="Concessional", subsidy_percent=50,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Tribe certificate","Project report"],
      source_url="https://tribal.nic.in/"),

    s(slug="dri-scheme", short_name="DRI", category="sc_st",
      name={"en":"Differential Rate of Interest Scheme","ta":"வேறுபட்ட வட்டி விகித திட்டம்","hi":"विभेदक ब्याज दर योजना"},
      department={"en":"RBI / Public Sector Banks","ta":"RBI / பொதுத்துறை வங்கிகள்","hi":"RBI / सार्वजनिक क्षेत्र के बैंक"},
      description={"en":"Concessional loans at 4% for weaker sections with income below poverty line.","ta":"வறுமைக் கோட்டிற்குக் கீழ் உள்ளவர்களுக்கு 4% சலுகை கடன்.","hi":"गरीबी रेखा से नीचे के लोगों के लिए 4% पर रियायती ऋण।"},
      min_age=18, max_age=60, max_income=72000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education=None,
      max_loan=15000, interest_rate="4%", subsidy_percent=0,
      moratorium="6 months", repayment_years="3 years",
      documents=["Aadhaar Card","Income certificate","Bank account"],
      source_url="https://www.rbi.org.in/"),

    s(slug="post-matric-sc", short_name="PMS-SC", category="sc_st",
      name={"en":"Post Matric Scholarship for SC Students","ta":"SC மாணவர்களுக்கு மெட்ரிக் பிந்தைய உதவித்தொகை","hi":"SC छात्रों के लिए पोस्ट मैट्रिक छात्रवृत्ति"},
      department={"en":"Ministry of Social Justice","ta":"சமூக நீதி அமைச்சகம்","hi":"सामाजिक न्याय मंत्रालय"},
      description={"en":"Scholarship for SC students pursuing post-matric education to reduce dropout.","ta":"SC மாணவர்களின் கல்வித் தொடர்ச்சிக்கு உதவித்தொகை.","hi":"SC छात्रों की शिक्षा जारी रखने के लिए छात्रवृत्ति।"},
      min_age=15, max_age=30, max_income=250000, eligible_categories=["SC"],
      eligible_genders=None, eligible_business_status=["new"], education="10th Pass",
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Caste certificate","Income certificate","Admission proof"],
      source_url="https://scholarships.gov.in/"),

    s(slug="top-class-sc", short_name="TCS-SC", category="sc_st",
      name={"en":"Top Class Education Scheme for SC Students","ta":"SC மாணவர்களுக்கு உயர்தர கல்வித் திட்டம்","hi":"SC छात्रों के लिए टॉप क्लास शिक्षा योजना"},
      department={"en":"Ministry of Social Justice","ta":"சமூக நீதி அமைச்சகம்","hi":"सामाजिक न्याय मंत्रालय"},
      description={"en":"Full scholarship for SC students in top-tier institutions (IITs, IIMs, NITs).","ta":"உயர்தர நிறுவனங்களில் SC மாணவர்களுக்கு முழு உதவித்தொகை.","hi":"शीर्ष संस्थानों में SC छात्रों के लिए पूर्ण छात्रवृत्ति।"},
      min_age=17, max_age=30, max_income=800000, eligible_categories=["SC"],
      eligible_genders=None, eligible_business_status=["new"], education="12th Pass",
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Caste certificate","Income certificate","Admission letter"],
      source_url="https://scholarships.gov.in/"),

    s(slug="nfhdc-loan", short_name="NHFDC", category="sc_st",
      name={"en":"NHFDC Loan for OBC/Minorities","ta":"OBC/சிறுபான்மையினருக்கு NHFDC கடன்","hi":"OBC/अल्पसंख्यकों के लिए NHFDC ऋण"},
      department={"en":"National Handicapped Finance & Dev Corp","ta":"தேசிய மாற்றுத்திறனாளர் நிதிக் கழகம்","hi":"राष्ट्रीय विकलांग वित्त निगम"},
      description={"en":"Concessional loans for persons with disabilities, OBC and minorities.","ta":"மாற்றுத்திறனாளிகள், OBC, சிறுபான்மையினருக்கு சலுகை கடன்.","hi":"दिव्यांगजनों, OBC और अल्पसंख्यकों के लिए रियायती ऋण।"},
      min_age=18, max_age=60, max_income=300000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=1500000, interest_rate="5% – 8%", subsidy_percent=0,
      moratorium="6 months", repayment_years="7 years",
      documents=["Aadhaar Card","Disability certificate (if applicable)","Income certificate"],
      source_url="https://www.nhfdc.nic.in/"),

    s(slug="sewb-scheme", short_name="SEWB", category="sc_st",
      name={"en":"Self Employment Scheme for Manual Scavengers","ta":"கைமுறை சுத்திகரிப்பாளர்களுக்கு சுய வேலைவாய்ப்பு","hi":"मैनुअल स्कैवेंजर्स के लिए स्वरोजगार योजना"},
      department={"en":"Ministry of Social Justice","ta":"சமூக நீதி அமைச்சகம்","hi":"सामाजिक न्याय मंत्रालय"},
      description={"en":"Financial assistance for manual scavengers and their dependents to start businesses.","ta":"கைமுறை சுத்திகரிப்பாளர்களுக்கு தொழில் தொடங்க நிதி உதவி.","hi":"मैनुअल स्कैवेंजर्स को व्यवसाय शुरू करने के लिए वित्तीय सहायता।"},
      min_age=18, max_age=60, max_income=None, eligible_categories=["SC","ST"],
      eligible_genders=None, eligible_business_status=["new"], education=None,
      max_loan=500000, interest_rate="Concessional", subsidy_percent=50,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Caste certificate","SEWB certificate"],
      source_url="https://socialjustice.gov.in/"),

    s(slug="post-matric-st", short_name="PMS-ST", category="sc_st",
      name={"en":"Post Matric Scholarship for ST Students","ta":"ST மாணவர்களுக்கு மெட்ரிக் பிந்தைய உதவித்தொகை","hi":"ST छात्रों के लिए पोस्ट मैट्रिक छात्रवृत्ति"},
      department={"en":"Ministry of Tribal Affairs","ta":"பழங்குடியினர் அமைச்சகம்","hi":"जनजातीय मामलों का मंत्रालय"},
      description={"en":"Scholarship for ST students in post-matric education with maintenance allowance.","ta":"ST மாணவர்களுக்கு கல்வி மற்றும் பராமரிப்பு உதவித்தொகை.","hi":"ST छात्रों के लिए शिक्षा और रखरखाव भत्ता।"},
      min_age=15, max_age=30, max_income=250000, eligible_categories=["ST"],
      eligible_genders=None, eligible_business_status=["new"], education="10th Pass",
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Tribe certificate","Income certificate","Admission proof"],
      source_url="https://scholarships.gov.in/"),

    s(slug="pre-matric-sc", short_name="PreMatric", category="sc_st",
      name={"en":"Pre Matric Scholarship for SC/ST Students","ta":"SC/ST மாணவர்களுக்கு மெட்ரிக் முன் உதவித்தொகை","hi":"SC/ST छात्रों के लिए प्री मैट्रिक छात्रवृत्ति"},
      department={"en":"Ministry of Social Justice","ta":"சமூக நீதி அமைச்சகம்","hi":"सामाजिक न्याय मंत्रालय"},
      description={"en":"Scholarship for SC/ST students in classes 9 and 10 to reduce dropout.","ta":"9, 10-ம் வகுப்பு SC/ST மாணவர்களுக்கு உதவித்தொகை.","hi":"9वीं, 10वीं कक्षा के SC/ST छात्रों के लिए छात्रवृत्ति।"},
      min_age=13, max_age=18, max_income=250000, eligible_categories=["SC","ST"],
      eligible_genders=None, eligible_business_status=["new"], education="Below 10th",
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Caste certificate","Income certificate","School proof"],
      source_url="https://scholarships.gov.in/"),

    # ============================================================
    # BATCH 8 — Agriculture & Rural (10)
    # ============================================================
    s(slug="agri-infra-fund", short_name="AIF", category="agriculture",
      name={"en":"Agriculture Infrastructure Fund","ta":"வேளாண் உள்கட்டமைப்பு நிதி","hi":"कृषि अवसंरचना कोष"},
      department={"en":"Ministry of Agriculture","ta":"வேளாண்மை அமைச்சகம்","hi":"कृषि मंत्रालय"},
      description={"en":"Medium-long term debt financing with 3% interest subvention for post-harvest infrastructure.","ta":"அறுவடைக்குப் பின் உள்கட்டமைப்புக்கு 3% வட்டி மானியம்.","hi":"कटाई के बाद की अवसंरचना के लिए 3% ब्याज सब्सिडी।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=20000000, interest_rate="9% (with 3% subsidy)", subsidy_percent=3,
      moratorium="6 – 12 months", repayment_years="7 years",
      documents=["Aadhaar Card","Project report","Land documents","Bank statements"],
      source_url="https://agriinfra.dac.gov.in/"),

    s(slug="micro-irrigation", short_name="MIF", category="agriculture",
      name={"en":"Micro Irrigation Fund","ta":"நுண் நீர்ப்பாசன நிதி","hi":"सूक्ष्म सिंचाई कोष"},
      department={"en":"NABARD","ta":"நபார்டு","hi":"नाबार्ड"},
      description={"en":"Subsidy up to 55% for drip and sprinkler irrigation systems.","ta":"சொட்டு மற்றும் தெளிப்பு நீர்ப்பாசனத்திற்கு 55% வரை மானியம்.","hi":"ड्रिप और स्प्रिंकलर सिंचाई के लिए 55% तक सब्सिडी।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=500000, interest_rate="As per bank", subsidy_percent=55,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Land documents","Water source proof"],
      source_url="https://pmksy.gov.in/"),

    s(slug="ahidf", short_name="AHIDF", category="agriculture",
      name={"en":"Animal Husbandry Infrastructure Development Fund","ta":"கால்நடை பராமரிப்பு உள்கட்டமைப்பு நிதி","hi":"पशुपालन अवसंरचना विकास कोष"},
      department={"en":"Ministry of Fisheries, Animal Husbandry","ta":"கால்நடை அமைச்சகம்","hi":"पशुपालन मंत्रालय"},
      description={"en":"3% interest subvention for dairy, meat processing and animal feed units.","ta":"பால், இறைச்சி பதப்படுத்துதல், கால்நடை தீவன அலகுகளுக்கு 3% வட்டி மானியம்.","hi":"डेयरी, मांस प्रसंस्करण, पशु आहार इकाइयों के लिए 3% ब्याज सब्सिडी।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=50000000, interest_rate="9% (with 3% subsidy)", subsidy_percent=3,
      moratorium="6 – 12 months", repayment_years="8 years",
      documents=["Aadhaar Card","Project report","Bank statements"],
      source_url="https://ahidf.udyamimitra.in/"),

    s(slug="fpo-scheme", short_name="FPO", category="agriculture",
      name={"en":"Formation and Promotion of FPOs","ta":"விவசாயிகள் உற்பத்தியாளர் அமைப்புகள்","hi":"किसान उत्पादक संगठन"},
      department={"en":"Ministry of Agriculture","ta":"வேளாண்மை அமைச்சகம்","hi":"कृषि मंत्रालय"},
      description={"en":"Support for forming and promoting Farmer Producer Organizations with credit guarantee.","ta":"விவசாயிகள் உற்பத்தியாளர் அமைப்புகளை உருவாக்க ஆதரவு.","hi":"किसान उत्पादक संगठनों के गठन के लिए सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education=None,
      max_loan=2000000, interest_rate="As per bank", subsidy_percent=0,
      moratorium="12 months", repayment_years="5 years",
      documents=["FPO registration","Members list","Business plan"],
      source_url="https://sfacfpo.dac.gov.in/"),

    s(slug="paramparagat-krishi", short_name="PKVY", category="agriculture",
      name={"en":"Paramparagat Krishi Vikas Yojana","ta":"பாரம்பரிய வேளாண் விகாஸ் யோஜனா","hi":"परंपरागत कृषि विकास योजना"},
      department={"en":"Ministry of Agriculture","ta":"வேளாண்மை அமைச்சகம்","hi":"कृषि मंत्रालय"},
      description={"en":"Support for organic farming clusters with certification and market linkage.","ta":"இயற்கை வேளாண் கிளஸ்டர்களுக்கு ஆதரவு.","hi":"जैविक खेती समूहों के लिए सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=500000, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Land documents","Cluster proposal"],
      source_url="https://pgsindia-ncof.gov.in/"),

    s(slug="e-nam", short_name="e-NAM", category="agriculture",
      name={"en":"National Agriculture Market (e-NAM)","ta":"தேசிய வேளாண் சந்தை","hi":"राष्ट्रीय कृषि बाजार"},
      department={"en":"Ministry of Agriculture","ta":"வேளாண்மை அமைச்சகம்","hi":"कृषि मंत्रालय"},
      description={"en":"Online trading platform for agricultural commodities with transparent pricing.","ta":"வேளாண் பொருட்களுக்கான ஆன்லைன் வர்த்தக தளம்.","hi":"कृषि जिंसों के लिए ऑनलाइन ट्रेडिंग प्लेटफॉर्म।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=0,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Land documents","Bank account"],
      source_url="https://www.enam.gov.in/"),

    s(slug="soil-health-card", short_name="SHC", category="agriculture",
      name={"en":"Soil Health Card Scheme","ta":"மண் வள அட்டை திட்டம்","hi":"मृदा स्वास्थ्य कार्ड योजना"},
      department={"en":"Ministry of Agriculture","ta":"வேளாண்மை அமைச்சகம்","hi":"कृषि मंत्रालय"},
      description={"en":"Free soil testing and recommendations for optimal fertilizer use.","ta":"இலவச மண் பரிசோதனை மற்றும் உர பரிந்துரைகள்.","hi":"मुफ्त मिट्टी परीक्षण और उर्वरक सिफारिशें।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Land documents"],
      source_url="https://soilhealth.dac.gov.in/"),

    s(slug="day-nrlm", short_name="DAY-NRLM", category="agriculture",
      name={"en":"Deendayal Antyodaya Yojana - NRLM","ta":"தீன்தயாள் அந்த்யோதய யோஜனா - NRLM","hi":"दीनदयाल अंत्योदय योजना - NRLM"},
      department={"en":"Ministry of Rural Development","ta":"ஊரக வளர்ச்சி அமைச்சகம்","hi":"ग्रामीण विकास मंत्रालय"},
      description={"en":"SHG-based livelihoods support for rural poor with credit and training.","ta":"ஊரக ஏழைகளுக்கு SHG அடிப்படையிலான வாழ்வாதார ஆதரவு.","hi":"ग्रामीण गरीबों के लिए SHG आधारित आजीविका सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=1000000, interest_rate="Concessional", subsidy_percent=50,
      moratorium="6 months", repayment_years="3 – 5 years",
      documents=["SHG membership","Aadhaar Card","Bank passbook"],
      source_url="https://aajeevika.gov.in/"),

    s(slug="svEP", short_name="SVEP", category="agriculture",
      name={"en":"Startup Village Entrepreneurship Programme","ta":"ஸ்டார்ட்அப் கிராம தொழில்முனைவு திட்டம்","hi":"स्टार्टअप विलेज एंटरप्रेन्योरशिप प्रोग्राम"},
      department={"en":"Ministry of Rural Development","ta":"ஊரக வளர்ச்சி அமைச்சகம்","hi":"ग्रामीण विकास मंत्रालय"},
      description={"en":"Support for rural youth to start enterprises in villages with handholding.","ta":"கிராமப்புற இளைஞர்கள் தொழில் தொடங்க ஆதரவு.","hi":"ग्रामीण युवाओं को उद्यम शुरू करने में सहायता।"},
      min_age=18, max_age=45, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new"], education=None,
      max_loan=500000, interest_rate="Concessional", subsidy_percent=25,
      moratorium="3 months", repayment_years="3 years",
      documents=["Aadhaar Card","Village certificate","Business plan"],
      source_url="https://aajeevika.gov.in/"),

    s(slug="rurban-mission", short_name="Rurban", category="agriculture",
      name={"en":"Shyama Prasad Mukherji Rurban Mission","ta":"ஷ்யாமா பிரசாத் முகர்ஜி ரூர்பன் இயக்கம்","hi":"श्यामा प्रसाद मुखर्जी रूरबन मिशन"},
      department={"en":"Ministry of Rural Development","ta":"ஊரக வளர்ச்சி அமைச்சகம்","hi":"ग्रामीण विकास मंत्रालय"},
      description={"en":"Development of rural growth clusters with economic activities and skills.","ta":"ஊரக வளர்ச்சி கிளஸ்டர்களின் வளர்ச்சி.","hi":"ग्रामीण विकास समूहों का विकास।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=500000, interest_rate="Concessional", subsidy_percent=30,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Village panchayat certificate","Business plan"],
      source_url="https://rurban.gov.in/"),

    # ============================================================
    # BATCH 9 — Textile / Handloom / Export (10)
    # ============================================================
    s(slug="samarth-handloom", short_name="SAMARTH", category="textile",
      name={"en":"SAMARTH — Handloom Cluster Development","ta":"சமர்த் — கைத்தறி கிளஸ்டர் மேம்பாடு","hi":"समर्थ — हथकरघा क्लस्टर विकास"},
      department={"en":"Ministry of Textiles","ta":"ஜவுளி அமைச்சகம்","hi":"वस्त्र मंत्रालय"},
      description={"en":"Cluster-based support for handloom weavers with design, marketing and skill training.","ta":"கைத்தறி நெசவாளர்களுக்கு கிளஸ்டர் அடிப்படையிலான ஆதரவு.","hi":"हथकरघा बुनकरों के लिए क्लस्टर आधारित सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=1000000, interest_rate="Concessional", subsidy_percent=50,
      moratorium="6 months", repayment_years="5 years",
      documents=["Weaver ID","Cluster membership","Bank passbook"],
      source_url="https://samarth-textiles.gov.in/"),

    s(slug="silk-samagra", short_name="Silk Samagra", category="textile",
      name={"en":"Silk Samagra Scheme","ta":"பட்டு சமக்ரா திட்டம்","hi":"सिल्क समग्र योजना"},
      department={"en":"Central Silk Board","ta":"மத்திய பட்டு வாரியம்","hi":"केंद्रीय रेशम बोर्ड"},
      description={"en":"End-to-end support for sericulture — from cocoon production to silk weaving.","ta":"பட்டு வளர்ப்பு — கூடு உற்பத்தி முதல் நெசவு வரை ஆதரவு.","hi":"रेशम उत्पादन से बुनाई तक समर्थन।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=1500000, interest_rate="Concessional", subsidy_percent=50,
      moratorium="12 months", repayment_years="5 – 7 years",
      documents=["Aadhaar Card","Land documents","Project report"],
      source_url="https://csb.gov.in/"),

    s(slug="powERTEX", short_name="PowerTex", category="textile",
      name={"en":"PowerTex India Scheme","ta":"பவர்டெக்ஸ் இந்தியா திட்டம்","hi":"पावरटेक्स इंडिया योजना"},
      department={"en":"Ministry of Textiles","ta":"ஜவுளி அமைச்சகம்","hi":"वस्त्र मंत्रालय"},
      description={"en":"Subsidy for powerloom units — modern looms, common facility centres.","ta":"பவர்லூம் அலகுகளுக்கு நவீன தறிகள், பொது வசதி மையங்கள் மானியம்.","hi":"पावरलूम इकाइयों के लिए आधुनिक करघा, सामान्य सुविधा केंद्र सब्सिडी।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=2000000, interest_rate="As per bank", subsidy_percent=30,
      moratorium="6 months", repayment_years="5 years",
      documents=["Udyam Registration","Project report","Bank statements"],
      source_url="https://texmin.nic.in/"),

    s(slug="technical-textiles", short_name="NTTM", category="textile",
      name={"en":"National Technical Textiles Mission","ta":"தேசிய தொழில்நுட்ப ஜவுளி இயக்கம்","hi":"राष्ट्रीय तकनीकी वस्त्र मिशन"},
      department={"en":"Ministry of Textiles","ta":"ஜவுளி அமைச்சகம்","hi":"वस्त्र मंत्रालय"},
      description={"en":"R&D and innovation support for technical textiles (medical, agricultural, protective).","ta":"தொழில்நுட்ப ஜவுளிக்கான R&D ஆதரவு.","hi":"तकनीकी वस्त्रों के लिए R&D सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=5000000, interest_rate="Grant", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","R&D proposal","Company registration"],
      source_url="https://nttm.texmin.gov.in/"),

    s(slug="pm-mitra", short_name="PM MITRA", category="textile",
      name={"en":"PM Mega Integrated Textile Region and Apparel Parks","ta":"PM மெகா ஒருங்கிணைந்த ஜவுளி பூங்காக்கள்","hi":"पीएम मेगा इंटीग्रेटेड टेक्सटाइल पार्क"},
      department={"en":"Ministry of Textiles","ta":"ஜவுளி அமைச்சகம்","hi":"वस्त्र मंत्रालय"},
      description={"en":"World-class textile infrastructure with plug-and-play facilities for manufacturers.","ta":"தயாரிப்பாளர்களுக்கு உலகத் தரம் வாய்ந்த ஜவுளி உள்கட்டமைப்பு.","hi":"निर्माताओं के लिए विश्व स्तरीय वस्त्र अवसंरचना।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=100000000, interest_rate="As per bank", subsidy_percent=0,
      moratorium="12 months", repayment_years="10 years",
      documents=["Company registration","Project report","Bank statements"],
      source_url="https://pmmitra.texmin.gov.in/"),

    s(slug="market-access-initiative", short_name="MAI", category="export",
      name={"en":"Market Access Initiative","ta":"சந்தை அணுகல் முயற்சி","hi":"बाजार पहुँच पहल"},
      department={"en":"Ministry of Commerce","ta":"வர்த்தக அமைச்சகம்","hi":"वाणिज्य मंत्रालय"},
      description={"en":"Financial assistance for exporters to participate in international trade fairs and BSMs.","ta":"சர்வதேச வர்த்தக கண்காட்சிகளில் பங்கேற்க நிதி உதவி.","hi":"अंतर्राष्ट्रीय व्यापार मेलों में भाग लेने के लिए सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=2000000, interest_rate="N/A", subsidy_percent=75,
      moratorium=None, repayment_years=None,
      documents=["IEC code","Company registration","Event registration"],
      source_url="https://commerce.gov.in/"),

    s(slug="interest-equalisation", short_name="IES", category="export",
      name={"en":"Interest Equalisation Scheme","ta":"வட்டி சமன்பாட்டுத் திட்டம்","hi":"ब्याज समकरण योजना"},
      department={"en":"DGFT, Ministry of Commerce","ta":"DGFT, வர்த்தக அமைச்சகம்","hi":"DGFT, वाणिज्य मंत्रालय"},
      description={"en":"Interest subsidy on pre and post-shipment rupee export credit for MSME exporters.","ta":"MSME ஏற்றுமதியாளர்களுக்கு வட்டி மானியம்.","hi":"MSME निर्यातकों के लिए ब्याज सब्सिडी।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=5000000, interest_rate="Subsidy 3% – 5%", subsidy_percent=5,
      moratorium=None, repayment_years="As per bank",
      documents=["IEC code","Udyam Registration","Bank statements"],
      source_url="https://dgft.gov.in/"),

    s(slug="transport-subsidy", short_name="TIES", category="export",
      name={"en":"Transport and Marketing Assistance for Specified Agriculture Products","ta":"வேளாண் ஏற்றுமதிக்கு போக்குவரத்து உதவி","hi":"कृषि निर्यात के लिए परिवहन सहायता"},
      department={"en":"Ministry of Commerce","ta":"வர்த்தக அமைச்சகம்","hi":"वाणिज्य मंत्रालय"},
      description={"en":"Assistance for transportation and marketing of specified agriculture products for export.","ta":"ஏற்றுமதிக்கான வேளாண் பொருட்கள் போக்குவரத்து உதவி.","hi":"निर्यात के लिए कृषि उत्पादों की परिवहन सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["IEC code","Shipping documents","Export invoices"],
      source_url="https://commerce.gov.in/"),

    s(slug="epcgi-tn", short_name="EPCG-TN", category="export",
      name={"en":"Export Promotion Council for Tamil Nadu","ta":"தமிழ்நாடு ஏற்றுமதி மேம்பாட்டு கவுன்சில்","hi":"तमिलनाडु निर्यात संवर्धन परिषद"},
      department={"en":"TN Department of Industries","ta":"தமிழ்நாடு தொழில்துறை","hi":"तमिलनाडु उद्योग विभाग"},
      description={"en":"Export promotion support, trade missions and buyer-seller meets for TN exporters.","ta":"தமிழ்நாடு ஏற்றுமதியாளர்களுக்கு ஏற்றுமதி மேம்பாட்டு ஆதரவு.","hi":"तमिलनाडु निर्यातकों के लिए निर्यात संवर्धन सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["IEC code","Company registration","Export history"],
      source_url="https://www.tn.gov.in/"),

    s(slug="nabard-export", short_name="NABARD-EX", category="export",
      name={"en":"NABARD Export Credit Support","ta":"நபார்டு ஏற்றுமதி கடன் ஆதரவு","hi":"नाबार्ड निर्यात ऋण सहायता"},
      department={"en":"NABARD","ta":"நபார்டு","hi":"नाबार्ड"},
      description={"en":"Export credit refinance to banks for agriculture and allied exports.","ta":"வேளாண் ஏற்றுமதிக்கு வங்கிகளுக்கு ஏற்றுமதி கடன் refinance.","hi":"कृषि निर्यात के लिए बैंकों को निर्यात ऋण पुनर्वित्त।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=5000000, interest_rate="Concessional", subsidy_percent=3,
      moratorium="6 months", repayment_years="3 years",
      documents=["IEC code","Project report","Bank statements"],
      source_url="https://www.nabard.org/"),

    # ============================================================
    # BATCH 10 — Housing / Health / Insurance / Misc (10)
    # ============================================================
    s(slug="pmay-gramin", short_name="PMAY-G", category="business",
      name={"en":"Pradhan Mantri Awaas Yojana - Gramin","ta":"பிரதம மந்திரி ஆவாஸ் யோஜனா - கிராமம்","hi":"प्रधानमंत्री आवास योजना - ग्रामीण"},
      department={"en":"Ministry of Rural Development","ta":"ஊரக வளர்ச்சி அமைச்சகம்","hi":"ग्रामीण विकास मंत्रालय"},
      description={"en":"Financial assistance up to ₹1.30 lakh for building pucca houses in rural areas.","ta":"ஊரக பகுதிகளில் வீடு கட்ட ₹1.30 லட்சம் வரை நிதி உதவி.","hi":"ग्रामीण क्षेत्रों में पक्का घर बनाने के लिए ₹1.30 लाख तक सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=130000, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","SECC data","Bank account","Land documents"],
      source_url="https://pmayg.nic.in/"),

    s(slug="pmay-urban", short_name="PMAY-U", category="business",
      name={"en":"Pradhan Mantri Awaas Yojana - Urban","ta":"பிரதம மந்திரி ஆவாஸ் யோஜனா - நகரம்","hi":"प्रधानमंत्री आवास योजना - शहरी"},
      department={"en":"Ministry of Housing & Urban Affairs","ta":"வீட்டுவசதி அமைச்சகம்","hi":"आवास मंत्रालय"},
      description={"en":"Housing for All urban mission with CLSS interest subsidy on home loans.","ta":"நகர்ப்புற வீட்டு வசதி திட்டம், வீட்டுக் கடனுக்கு வட்டி மானியம்.","hi":"शहरी आवास मिशन, गृह ऋण पर ब्याज सब्सिडी।"},
      min_age=21, max_age=None, max_income=1800000, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=1200000, interest_rate="6.5% – 8.5%", subsidy_percent=6,
      moratorium=None, repayment_years="20 years",
      documents=["Aadhaar Card","Income certificate","Property documents"],
      source_url="https://pmaymis.gov.in/"),

    s(slug="ayushman-bharat", short_name="AB-PMJAY", category="business",
      name={"en":"Ayushman Bharat PM-JAY","ta":"ஆயுஷ்மான் பாரத் PM-JAY","hi":"आयुष्मान भारत PM-JAY"},
      department={"en":"Ministry of Health & Family Welfare","ta":"சுகாதார அமைச்சகம்","hi":"स्वास्थ्य मंत्रालय"},
      description={"en":"Health cover of ₹5 lakh/family/year for secondary and tertiary hospitalization.","ta":"குடும்பத்திற்கு ஆண்டுக்கு ₹5 லட்சம் மருத்துவ காப்பீடு.","hi":"परिवार को वार्षिक ₹5 लाख स्वास्थ्य कवर।"},
      min_age=0, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=500000, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Ration Card","SECC data"],
      source_url="https://pmjay.gov.in/"),

    s(slug="pm-suraksha-bima", short_name="PMSBY", category="business",
      name={"en":"Pradhan Mantri Suraksha Bima Yojana","ta":"பிரதம மந்திரி சுரக்ஷா பீமா யோஜனா","hi":"प्रधानमंत्री सुरक्षा बीमा योजना"},
      department={"en":"Ministry of Finance","ta":"நிதி அமைச்சகம்","hi":"वित्त मंत्रालय"},
      description={"en":"Accident insurance of ₹2 lakh at ₹20/year premium for bank account holders.","ta":"வங்கிக் கணக்கு வைத்திருப்பவர்களுக்கு ₹20/ஆண்டு பிரீமியத்தில் ₹2 லட்சம் விபத்து காப்பீடு.","hi":"बैंक खाताधारकों के लिए ₹20/वर्ष प्रीमियम पर ₹2 लाख दुर्घटना बीमा।"},
      min_age=18, max_age=70, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=0,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Bank account"],
      source_url="https://www.jansuraksha.gov.in/"),

    s(slug="pmjjby", short_name="PMJJBY", category="business",
      name={"en":"Pradhan Mantri Jeevan Jyoti Bima Yojana","ta":"பிரதம மந்திரி ஜீவன் ஜோதி பீமா","hi":"प्रधानमंत्री जीवन ज्योति बीमा योजना"},
      department={"en":"Ministry of Finance","ta":"நிதி அமைச்சகம்","hi":"वित्त मंत्रालय"},
      description={"en":"Life insurance of ₹2 lakh at ₹436/year for bank account holders aged 18-50.","ta":"18-50 வயதுடைய வங்கி கணக்குதாரர்களுக்கு ₹436/ஆண்டு பிரீமியத்தில் ₹2 லட்சம் ஆயுள் காப்பீடு.","hi":"18-50 वर्ष के बैंक खाताधारकों के लिए ₹436/वर्ष पर ₹2 लाख जीवन बीमा।"},
      min_age=18, max_age=50, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=0,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Bank account"],
      source_url="https://www.jansuraksha.gov.in/"),

    s(slug="atal-pension", short_name="APY", category="business",
      name={"en":"Atal Pension Yojana","ta":"அடல் பென்ஷன் யோஜனா","hi":"अटल पेंशन योजना"},
      department={"en":"PFRDA","ta":"PFRDA","hi":"PFRDA"},
      description={"en":"Guaranteed minimum pension of ₹1,000 to ₹5,000/month after age 60.","ta":"60 வயதுக்குப் பிறகு ₹1,000 முதல் ₹5,000 வரை உத்தரவாத ஓய்வூதியம்.","hi":"60 वर्ष के बाद ₹1,000 से ₹5,000/माह तक गारंटीड पेंशन।"},
      min_age=18, max_age=40, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=50,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Bank account"],
      source_url="https://www.npscra.nsdl.co.in/"),

    s(slug="pm-svanidhi-2", short_name="PM SVANidhi-2", category="business",
      name={"en":"PM SVANidhi 2.0","ta":"PM சுவநிதி 2.0","hi":"पीएम स्वनिधि 2.0"},
      department={"en":"Ministry of Housing & Urban Affairs","ta":"வீட்டுவசதி அமைச்சகம்","hi":"आवास मंत्रालय"},
      description={"en":"Enhanced working capital loans up to ₹50,000 with digital transaction incentives.","ta":"டிஜிட்டல் பரிவர்த்தனை ஊக்கத்தொகையுடன் ₹50,000 வரை மூலதனக் கடன்.","hi":"डिजिटल लेनदेन प्रोत्साहन के साथ ₹50,000 तक कार्यशील पूंजी ऋण।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["existing"], education=None,
      max_loan=50000, interest_rate="7% interest subsidy", subsidy_percent=7,
      moratorium=None, repayment_years="1 year",
      documents=["Aadhaar Card","Vendor certificate","Bank account"],
      source_url="https://pmsvanidhi.mohua.gov.in/"),

    s(slug="standup-mitra", short_name="SUM", category="sc_st",
      name={"en":"Stand-Up Mitra Portal","ta":"ஸ்டாண்ட்-அப் மித்ரா தளம்","hi":"स्टैंड-अप मित्र पोर्टल"},
      department={"en":"SIDBI","ta":"SIDBI","hi":"SIDBI"},
      description={"en":"Handholding support for SC/ST and women entrepreneurs to access Stand-Up India loans.","ta":"SC/ST மற்றும் பெண் தொழில்முனைவோருக்கு ஸ்டாண்ட்-அப் இந்தியா கடன் அணுகல் ஆதரவு.","hi":"SC/ST और महिला उद्यमियों के लिए स्टैंड-अप इंडिया ऋण पहुँच सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=["SC","ST","General"],
      eligible_genders=["female"], eligible_business_status=["new"], education=None,
      max_loan=10000000, interest_rate="As per bank", subsidy_percent=0,
      moratorium="18 months", repayment_years="7 years",
      documents=["Aadhaar Card","Caste certificate (if applicable)","Project report"],
      source_url="https://www.standupmitra.in/"),

    s(slug="bharat-ke-veer", short_name="BKV", category="business",
      name={"en":"Bharat ke Veer","ta":"பாரத் கே வீர்","hi":"भारत के वीर"},
      department={"en":"Ministry of Home Affairs","ta":"உள்துறை அமைச்சகம்","hi":"गृह मंत्रालय"},
      description={"en":"Financial assistance to families of martyred paramilitary personnel.","ta":"வீரமரணம் அடைந்த பாதுகாப்புப் பணியாளர்களின் குடும்பங்களுக்கு நிதி உதவி.","hi":"शहीद अर्धसैनिक कर्मियों के परिवारों को वित्तीय सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=CATS,
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=None, interest_rate="N/A", subsidy_percent=100,
      moratorium=None, repayment_years=None,
      documents=["Aadhaar Card","Martyr certificate","Bank account"],
      source_url="https://bharatkeveer.gov.in/"),

    s(slug="scst-obc-hub", short_name="SC-ST Hub", category="sc_st",
      name={"en":"SC-ST-OBC Business Facilitation Hub","ta":"SC-ST-OBC வணிக வசதி மையம்","hi":"SC-ST-OBC व्यवसाय सुविधा हब"},
      department={"en":"Ministry of MSME","ta":"MSME அமைச்சகம்","hi":"MSME मंत्रालय"},
      description={"en":"Single-window support for SC/ST/OBC entrepreneurs — training, credit, procurement.","ta":"SC/ST/OBC தொழில்முனைவோருக்கு ஒற்றை சாளர ஆதரவு.","hi":"SC/ST/OBC उद्यमियों के लिए एकल खिड़की सहायता।"},
      min_age=18, max_age=None, max_income=None, eligible_categories=["SC","ST","OBC","BC","MBC"],
      eligible_genders=None, eligible_business_status=["new","existing"], education=None,
      max_loan=5000000, interest_rate="Concessional", subsidy_percent=25,
      moratorium="6 months", repayment_years="5 years",
      documents=["Aadhaar Card","Caste certificate","Udyam Registration"],
      source_url="https://www.scsthub.in/"),
]


def run():
    db = SessionLocal()
    added, skipped = 0, 0
    try:
        for s in SCHEMES:
            existing = db.query(Scheme).filter(Scheme.slug == s["slug"]).first()
            if existing:
                skipped += 1
                continue
            db.add(Scheme(**s))
            added += 1
        db.commit()
        total = db.query(Scheme).count()
        print(f"[OK] Added: {added}, Skipped: {skipped}")
        print(f"[OK] Total schemes in DB: {total}")
    finally:
        db.close()


if __name__ == "__main__":
    run()